### ISSUE TITLE
Settings Flyout Background Not Working in 1.2.3

### ISSUE THREAD

**Issue by girishnuli** [timheuer/callisto#100]
Hi Tim,

Setting the background brush for settings flyout was working correctly until I updated to v1.2.3 via extensions update in VS. 

The background color is always white irrespective of what has been set in code behind. I just downloaded the source code of callisto and ran the sample app with a custom background brush, and it had the same issue.

Would be great if this can be fixed or if you can let me know how to correct it.

Thanks.

**Comment by timheuer** [comment]
See https://github.com/timheuer/callisto/issues/81 for the change and how to override.

**Comment by timheuer** [comment]
Related to the fix for #81 -- see that for the properties to set for the breaking change
