### ISSUE TITLE
Need to change width of flyout dynamically

### ISSUE THREAD

**Issue by falafelsoftware** [timheuer/callisto#108]
Tim, I just switched from my custom settings control to yours, great work!
I have one quirk: the small size is fine most of the time, but I need to switch to a 800 pixel wide size when a certain option is chose in the user control that I set as your content.
This requires two things
1. To set the width to a different value than the 2 provided
2. To do that after the control has been shown.
I tried 2 by switching from Narrow to Wide (my settings control.Parent as SettingsFlyout).FlyoutWidth = ..., but that had no effect.
So I am stuck on both parts.
What would you recommend?

**Comment by timheuer** [comment]
800px is not a specified size for the SettingsFlyout experience.  I would
encourage you to keep it "Wide" format and fit your UX within that if using
the SettingsFlyout.

---

http://timheuer.com/blog/
twitter: @timheuer

On Sun, Oct 21, 2012 at 11:40 PM, Falafel Software <notifications@github.com
