### ISSUE TITLE
Flyout incorrectly position on extended desktop

### ISSUE THREAD

**Issue by AchinthaK** [timheuer/callisto#109]
When I use my 2nd screen to run the app, the right aligned flyouts are appear on the very top of the screen (see the image- http://dl.dropbox.com/u/110199831/1E5AF92D-DB63-4A28-B9AB-BC89E31E1504.png)

As a fix I had to change following code segments (see the image - http://dl.dropbox.com/u/110199831/B0DC2532-D226-4758-A382-76F688A058C2.png), it may not be the best fix, but it does the job for now. See the image for fix - http://dl.dropbox.com/u/110199831/6EAE71A5-2ED2-438A-8D22-3F7D3041DF22.png

**Comment by timheuer** [comment]
In this case how are your monitors positioned?

-th

**Comment by AchinthaK** [comment]
1st Screen - Left
2nd Screen - Right
Orientation - Landscape
Resolution - 1920x1080
Is that what you are after?
