### ISSUE TITLE
AppManifestHelper crash if you use non hex color in appmanifest

### ISSUE THREAD

**Issue by Kuirak** [timheuer/callisto#110]
You can't compile if you use  white  instead of #FFFFFF in your package.appmanifest.

it should although handle  color strings.

**Comment by timheuer** [comment]
There is no WinRT API to convert from a named string value to Windows.UI.Color unfortunately.  This makes this challenge difficult :-)

**Comment by dotMorten** [comment]
How about this:
var colorProp = System.Reflection.RuntimeReflectionExtensions.GetRuntimeProperty(typeof(Windows.UI.Colors), "AliceBlue");
if (colorProp != null)
{
    var color = (Windows.UI.Color)colorProp.GetValue(null);
}
