### ISSUE TITLE
Issue with Settings Flyout and Height

### ISSUE THREAD

**Issue by csmaster2005** [timheuer/callisto#111]
How is the height of the Settings Flyout calculated?
The issue is that I have a listview inside of the settings flyout. If this listview is long, the listview does not expand to the size of the settings flyout. Instead, it grows as long as needed, and instead the settingsflyout itself scrolls.

The issue thus is, how can I have a long listview scroll itself, instead of the settings flyout scrolling?

**Comment by timheuer** [comment]
The height of the overall settings flyout is calculated based on the window
height for the current view.  There is a ScrollViewer hosting the content
within the area as you've noted.  If you wanted your ListView to be
scrollable itself you'd set a height on it to bound it to something that
would require scrolling.

**Comment by csmaster2005** [comment]
Then is there a way to disable the ScrollViewer? I think what I'm trying would be a fairly common scenario, and outside of programmatically checking the height of the flyout and then setting the listview to be a number based on that, I'm not sure how to do it. Ideally I'd want to handle that on the XAML side, and not in code.

**Comment by timheuer** [comment]
You can re-template to remove the scrollviewer but it is intentional to
ensure content can scroll.  It sounds like what you have is a situation
where you have scrollable content (listview) within scrollable content
(other settings in the panel).  Again if you just set the ListView to a
size this should work.  Do you have a screenshot of what you are trying to
achieve?

**Comment by csmaster2005** [comment]
I don't have a screenshot, but imagine this scenario - 
I want to have a fixed title, and then beneath it I want to render a list of items. I want the title to always be fixed in place, whereas the user can scroll the listview beneath it.

Currently, the entire flyout scrolls, thus if the user scrolls down the title goes off screen.

I _could_ do as you said and in my constructor check the flyout height and set the listview to be the height minus the space needed for the title - but that feels like a hack, at best. I'm happy to hear any suggestions you may have :)

**Comment by timheuer** [comment]
Hmm, here is an example: http://sdrv.ms/VKwa3k

```
<StackPanel>
            <TextBlock FontSize="53" Text="Some header text" />
            <ListView x:Name="ListOfStuff" Height="400"/>
        </StackPanel>
```

**Comment by csmaster2005** [comment]
Yes that would do it, but I want the ListView to scale to the size of the parent.

Your example above would not look good on small resolution or high resolution devices, since it's fixed to 400. What I really want is the textblock will take some fixed number of pixels, and then the ListView will take the rest.

**Comment by timheuer** [comment]
Yes in this case you'd have to manage your own panel content to have that "locked" header feel.

**Comment by csmaster2005** [comment]
Can you please let me know what the simplest way to re-template it to remove the scroll viewer is?

**Comment by timheuer** [comment]
I'm not sure how removing the scrollviewer is going to solve your problem.
But to re-template, you'll make a copy of the definition of SettingsFlyout
from generic.xaml.
