### ISSUE TITLE
SettingsFlyout from left side?

### ISSUE THREAD

**Issue by csmaster2005** [timheuer/callisto#112]
Does the library currently support making the flyout come from the left side and not right? I don't see anything regarding it, but thought I'd ask. If not, do you mind pointing me to the place to look to change this? I can submit a pull request to add the functionality if you'd like.

**Comment by timheuer** [comment]
Set the Placement to Top/Left/Right/Bottom. The flyout will attempt to use
your preference, but based on the window bounds, etc. it will position it
'correctly' in accordance with UI guidelines.

**Comment by csmaster2005** [comment]
Sorry if I wasn't clear - I am talking about the SettingsFlyout (have it flyout from the left side) and not the standard Flyout object.

**Comment by timheuer** [comment]
Oh, no there is not a way to have it come in by default from the other
side.  I won't make that change because that breaks UI guidance.  However
if the user's OS was a right-to-left language it will do this for you.
