### ISSUE TITLE
Hover VisualState for ToggleMenuItem Checkbox

### ISSUE THREAD

**Issue by bobwiller** [timheuer/callisto#115]
I have styled a Flyout Menu that contains several ToggleMenuItems, and everything looks great.  The only thing I don't seem to be able to change is the hover style for the Checkmark itself.  The style for ToggleMenuItem has a hover VisualState, but the style for ToggleMenuItemCheckBox does not. So now when rolling over my menu the style of the text for the checkbox changes, but the tick mark does not.  Am I looking in the wrong place or is it not currently handled?

Thanks,
Bob

**Comment by timheuer** [comment]
doh!  looks like a legit bug...not currently handled.

---

http://timheuer.com/blog/
twitter: @timheuer

**Comment by timheuer** [comment]
Actually there is one there -- it isn't called Hover, but rather PointerOver -- bad on me for naming :-(
