### ISSUE TITLE
Assembly Should be Signed with a Strong Name

### ISSUE THREAD

**Issue by ndavidsmk** [timheuer/callisto#118]
Attempting to reference Callisto from an assembly signed with a strong name key fails with the following error:

Error 20    Assembly generation failed -- Referenced assembly 'Callisto' does not have a strong name

Please consider signing the Callisto assemblies with a strong name as described here http://msdn.microsoft.com/en-us/library/xc31ft41.aspx

**Comment by cyotek** [comment]
Same issue, a strong name would be appreciated!

**Comment by tibel** [comment]
Yes, please add strong name.

**Comment by reinierdg** [comment]
Yes, please sign the assembly before publishing it as NuGet package.

**Comment by timheuer** [comment]
@reinerdg it has already been published as a package

**Comment by reinierdg** [comment]
Yes, I see it is on NuGet, but Callisto.dll is not signed. You can see that when you reference it in your app and check the properties. It says: Strong Name: False.

**Comment by timheuer** [comment]
Yes I know it isn't signed as I'm the publisher :-). Strong naming doesn't have a significant benefit and I have to take into account other dependencies at this point that may break people the other way if it suddenly is signed. Because of that I've decided not to sign it.

**Comment by reinierdg** [comment]
Ok I understand, thanks for your time.

**Comment by tonyt123456** [comment]
Hi Tim,
Great job on this package, I love it.   Would you consider having a signed branch of the control?   I have an enterprise app that requires only strong name assemblies  (On an enterprise deployment not through windows store you have to have strong signed assemblies so you can side load without needing a developer licence installed on all machines).      

Thanks,
Tony

**Comment by b0c1** [comment]
+1 tonyt123456
