### ISSUE TITLE
Animate CustomDialog

### ISSUE THREAD

**Issue by odelvalle** [timheuer/callisto#120]
Hi..

I want to include PopupThemeTransition in custom dialog when is displayed and also I want to animate position if the touch keyboard appears

I've updated the code and template in CustomDialog to support these features but I don't know if exist any other way to do this without having to make any changes.

Regards

**Comment by timheuer** [comment]
Animating of the UI dialog is not a part of the default dialog behavior which this aims to match. 

They keyboard should be working already. If it isn't I must have not added the code in my checkin. It would only move the dialog if needed. 

-th

**Comment by odelvalle** [comment]
thanks tim, I remove PopupThemeTransition, you are right... 

Animate the dialog if touch keyboard is showing work strange. Animate occurs over all page content and not over Dialog only.I'm looking anímate only dialog content and not all content.

Thanks again.. good job
