### ISSUE TITLE
Custom Dialog needs higher ZIndex

### ISSUE THREAD

**Issue by lfoust** [timheuer/callisto#126]
I am hitting a situation where a Custom Dialog is being covered up by another control. It seems to reason that since it is a dialog it should be set to some reasonably high ZIndex so this will not happen.

**Comment by timheuer** [comment]
Which control?  If a WebView this is expected. If another control you can control the zindex by placing in your tree appropriately

-th

**Comment by lfoust** [comment]
You’re right. It is the WebView. It looks like I may need to workaround the problem by hiding the webview when the dialog is visible.

**Comment by timheuer** [comment]
Or switch it to a webviewbrush

-th
