### ISSUE TITLE
FlipViewIndicator when FlipView item list changes

### ISSUE THREAD

**Issue by pcolmer** [timheuer/callisto#128]
I've got a FVI bound to a FV. The user clicks on something in the UI which causes the list of items bound to the FV to be rebuilt.

The FVI correctly updates with the number of items in the list, but it does NOT mark the first item as the selected item.

I've tried explicitly setting the SelectedIndex on the FV to 0 to try and force the FVI to update which item is selected but that hasn't made any difference.

**Comment by timheuer** [comment]
I am not able to repro this.  In fact the Callisto test app does this and the indicator does get reset.

**Comment by pcolmer** [comment]
Just in case someone else has a similar issue, my problem was being caused by the fact that I was changing the members of the list, and not the list itself which is what the Callisto test app does. I managed to resolve the problem by remembering the source, setting the FVI source to null and then setting it back to the original value. It then works as per the test app.
