### ISSUE TITLE
Why to make Flyout as IDisposable?

### ISSUE THREAD

**Issue by xperiandri** [timheuer/callisto#130]
Flyout does not use any direct unmanaged resource, so why to implement it as IDisposable?

And how do you imagine its usage as IDisposable?

**Comment by timheuer** [comment]
Because this current implementation uses a visual element not within the
app's visual tree it is possible to have a leak.  I added this for GC
cleanup when the flyout is closed.

---

http://timheuer.com/blog/
twitter: @timheuer

**Comment by tibel** [comment]
Shouldn't it be the same with SettingsFlyout?
