### ISSUE TITLE
CustomDialog Background

### ISSUE THREAD

**Issue by bbeda** [timheuer/callisto#131]
Right now, if I want to use CustomDialog without setting a background, it crashes with relatively hard to debug error. It says there is an error with a Foreground property somwhere at a line/position in no file and the you have to dig to find out what's going on. I think it would make sense to set a default background for CustomDialog and let user decide when she changes the color. Also, current behaviors doesn't make sense if  someones job is to create the structure/layout and services of an app, not styles.

**Comment by timheuer** [comment]
Background color is required per the UI guidelines.  Default color is a good bug to fix though.
