### ISSUE TITLE
WatermarkTextBox with passwordbox

### ISSUE THREAD

**Issue by YoungjaeKim** [timheuer/callisto#133]
Thanks for your good sharing.
As I try to use WatermarkTextBox in ID/Password textboxes which displays "enter ID here" and "enter password here" words, Callisto cannot use passwordbox with watermark.

Can you provide the feature?

**Comment by timheuer** [comment]
it is a limitation of passwordbox actually...cannot do this.

---

http://timheuer.com/blog/
twitter: @timheuer
