### ISSUE TITLE
CustomDialog Button keeps PointerOver state

### ISSUE THREAD

**Issue by bluebasher** [timheuer/callisto#135]
I'm not sure if this is a Callisto issue or WinRT.

When I close the Custom Dialog by pressing one of the Buttons (with the mouse) the state of the button is still PointerOver (eg IsPointerOver == true) the next time the dialog is shown.

I've tried VisualStateManager.GoToState(CloseButton, "Normal", false); but that doesn't reset the state, although it returns true.

The same issue is in the CustomDialog sample provided but is less obvious because of the colorschema.

Can you advice what can be done about this?
Thanks for your help!

**Comment by timheuer** [comment]
This is a WinRT bug unfortunately

-th
