### ISSUE TITLE
WinRT information: The type 'BrushToColorConverter' was not found.

### ISSUE THREAD

**Issue by yoitsro** [timheuer/callisto#138]
When debugging on WinRT, I get the error: WinRT information: The type 'BrushToColorConverter' was not found.

When debugging on Windows 8, I don't get these problems. I'm not entirely sure why this is happening, but it's rather frustrating :(

Please help :)

**Comment by timheuer** [comment]
I don't understand the difference between "Windows 8" and "WinRT" -- they
are the same if you are using this library.  Please describe how you are
using this library and provide repro steps.

**Comment by yoitsro** [comment]
I'm using the package found on NuGet. I'm using it as the demos show. I'm remote debugging on an Asus Vivo Tab RT (ie, the ARM architecture). When I do this, I receive the following issue when I try to navigate to the page containing the control:

![winrt.png](https://f.cloud.github.com/assets/3006852/3746/cd596700-42e1-11e2-9481-b4196448dd8b.png)

Would a stacktrace be helpful?

**Comment by timheuer** [comment]
Not really.  It looks like the package is not containing the right bits.
Can you confirm on the remote device you see Callisto in the package
directory with the generic.xaml there?

**Comment by yoitsro** [comment]
As I'm remote debugging, I'm not 100% sure where it's putting the package, but I think it's at C:\Users\UserName\AppData\Local\Packages\PackageID. Is that right? If so, I'm not seeing the Callisto directory/package.

**Comment by timheuer** [comment]
This might be hard for me to debug without seeing the machine.  It sounds
like the problem is something missing in the package.  One thing might try
is to actually create a package and then install that on the other machine
to see if there is a difference in remote debug versus installing the
package.

**Comment by yoitsro** [comment]
I can confirm that the Generic.xaml file is definitely in the package folder located at C:\Users\UserName\AppxLayout\PackageID\Callisto\themes.

**Comment by dotMorten** [comment]
What about 'BrushToColorConverter' ? Is it defined in there or any where else?

**Comment by yoitsro** [comment]
It is defined in there and there only.

**Comment by timheuer** [comment]
Are you using BrushToColorConverter anywhere else in _your_ app?  What I
mean here is outside of any Callisto control.

**Comment by yoitsro** [comment]
Definitely not used anywhere else in my app.

**Comment by yoitsro** [comment]
I don't suppose you have an RT device to test on, do you?

**Comment by timheuer** [comment]
I've tested on my Surface device and cannot reproduce it.
