### ISSUE TITLE
VariableSizedWrapGrid that supports incremental loading.

### ISSUE THREAD

**Issue by pregress** [timheuer/callisto#141]
As you can see here: http://stackoverflow.com/questions/13847632/isupportincrementalloading-combined-with-variablesizedwrapgrid 

If you set the ItemsPanelTemplate to a VariableSizedWrapGrid, you lose the Incremental Loading of the collection.

Feature request:
Can somebody implement a  VariableSizedWrapGrid that support incremental loading of items?

**Comment by timheuer** [comment]
Just being realistic by closing this feature request.  This is not something I'm going to tackle.  The issue of virtualized content + incremental loading is a challenging one and requires more than just a wrap grid (needs new panel support)
