### ISSUE TITLE
Only works in Sample Project

### ISSUE THREAD

**Issue by nhdmalik** [timheuer/callisto#143]
Hi all,
It only work in sample project but not in my project. Even though I added the reference and page from the sample project in another project it does not work at all. Do not show rating control in design and run time.
Can anyone tell what is else required to run it properly?
Thanks
Naeem

**Comment by timheuer** [comment]
How are you adding the reference?  Adding a reference to the dll only will not work. See readme for installation. Also design-time is know to have a few issues as this was written to work in runtime but I haven't spent the extra time for a great design-time experience. 

-th

**Comment by nhdmalik** [comment]
Thanks. I got it. I was adding reference from local path instead of from Extensions. Now its working.
