### ISSUE TITLE
Theme issue with Flyout control

### ISSUE THREAD

**Issue by zimmyzhou** [timheuer/callisto#145]
I'm having problems using Flyout control. When Setting the App RequestedTheme to dark, flyout control opened with a white background, but the child control of the flyout is applied to the dark theme(most of them have white foreground and border brush, such as TextBlock.Text and TextBox.BorderBrush ), in this case, all the controls have the same foreground color as the background, which makes them invisible. Is there anything I can do to solve this problem?

**Comment by timheuer** [comment]
This is a known issue...you have to re-template any control you want to be
hosted in there.  Yes it is annoying.  This is a platform limitation that
there can only be one theme in WinRT at a time.
