### ISSUE TITLE
Style back button and header text in SettingsFlyout 

### ISSUE THREAD

**Issue by vondwater** [timheuer/callisto#146]
Hi,

I'm trying to edit the pointerover and pressed color of the back button in the SettingsFlyout. I thought I override the SettingsBackButtonStyle2 style in my StandardStyles.xaml but it doesn't seem to work. How can i edit the style of the back button?

In version 1.0.0 of the callisto controls I had my header title of the SettingsFlyout in another color then white. After my update to the 1.2.6 version my style has dissapeared.

I used this to populate my SettingsFlyout:
var settings = new SettingsFlyout
                    {
                        Content = new AccountControl(),
                        HeaderText = "MY ACCOUNT",
                        IsOpen = true,
                        Style = (Style)Application.Current.Resources["FlyoutText"],
                        ContentBackgroundBrush = new SolidColorBrush() { Color = Color.FromArgb(255, 0, 0, 0) },
                        ContentForegroundBrush = new SolidColorBrush() { Color = Color.FromArgb(255, 255, 196, 33) },
                    };
In my xaml style I have:

<Style x:Key="FlyoutText" TargetType="callisto:SettingsFlyout">
      <Setter Property="FontFamily" Value="{StaticResource Interstate-Light}"/>
      <Setter Property="Foreground" Value="{StaticResource Yellow}"/>
</Style>

**Comment by vondwater** [comment]
I'm sorry. Didn't need to post this. I have overwritten the SettingsBackButtonStyle2 style in the Generic.Xaml file.

Problem solved!

**Comment by timheuer** [comment]
One thing to keep in mind is this doesn't really align with the consistency
in UI guidelines...which is why I didn't make it easy to change these.
