### ISSUE TITLE
flyout-debugger.break when pressed?...vb

### ISSUE THREAD

**Issue by dremerald** [timheuer/callisto#148]
I have 4 different flyouts, with all different menu's inside of them.  But if I click a button to display one menu and dismiss it and click the next button to display it's menu my program crashes (I can open  and dismiss the same menu (click the same button) over and over and over again and everything's fine) but when I click to display another flyout, it crashes.....

It always comes back to this in app.g.i.vb:
# If Debug AndAlso Not DISABLE_XAML_GENERATED_BREAK_ON_UNHANDLED_EXCEPTION Then

```
    AddHandler Me.UnhandledException,
        Sub(sender As Global.System.Object, unhandledExceptionArgs As Global.Windows.UI.Xaml.UnhandledExceptionEventArgs)
            If Global.System.Diagnostics.Debugger.IsAttached Then
                !!!!!!Global.System.Diagnostics.Debugger.Break()!!!!!
            End If
        End Sub
```
# End If

and this is the output from the debugger:

callstack:      appname.exe!appname.App.(Object sender, Windows.UI.Xaml.UnhandledExceptionEventArgs unhandledExceptionArgs) Line 63 + 0x5 bytes    Basic (line 63 is this: Global.System.Diagnostics.Debugger.Break())
Exception:      {"No installed components were detected. (Exception from HRESULT: 0x800F1000)"} System.Exception
Message:      "System.Exception at Windows.UI.Xaml.FrameworkElement.MeasureOverride(Size availableSize) at Windows.UI.Xaml.UIElement.Measure(Size availableSize) at Callisto.Controls.Flyout.OnHostPopupOpened(Object sender, Object e)"    String

Very sorry if this has already been answered, or if it's just a silly mistake on my part but by the looks of it, there isn't enough space in the menu? not sure anyway any help would be much appreciated

Thanks!

**Comment by timheuer** [comment]
can you provide a repro scenario?

**Comment by dremerald** [comment]
yep sure:
I can imagen you wanting to throw the monitor out the window after reading my code, just so you know I'm new to vb...and everything else.  

here's a mock of what I'm trying to do, basic ideas are there:
<a href="http://ipto.com.au/pub/Stanthorpe%20SHS/gcamp7/app2.zip" target="_blank">mock</a> 

situation:
when you click a menu the flyout will display (you can repeatedly click the same button and all will be fine)
but if you dismiss the file menu (as an example) and click on say the view menu it will crash.
so, switching menu's causes the debugger to break.  
if you can't understand me, just start clicking the buttons and going between them and you'll see.

**Comment by dremerald** [comment]
here is a video demonstrating the problem:
http://www.youtube.com/watch?v=Z7b0gwY6vM8&feature=

Using the mock project I linked above you can achieve the same results as this video.

**Comment by dremerald** [comment]
I'm very sorry for the trouble, the problem was with MY code and it's my fault.  if anyone is interested in what my problem was, it was I was trying to to add the same variable into 2 different flyouts at the same time (mi14) and apparently that isn't good as it was generating an unhanded exception.  Everything seems to be working thanks for releasing these controls to the public they are a great help!
