### ISSUE TITLE
Payload file error

### ISSUE THREAD

**Issue by tallichet** [timheuer/callisto#151]
I have a Compilation error since I've updated to Callisto v1.2.6

The error says: 

```
Payload file [...]Win8-Common\Common\bin\Debug\Callisto\themes\Generic.xaml' does not exist.
```

If I add a Generic.xaml file, I have the following error. 

```
Payload contains two or more files with the same destination path 'Callisto\themes\Generic.xaml'. Source files: 
[...]App\bin\Debug\Callisto\themes\Generic.xaml
[...]packages\Callisto.1.2.6\lib\winrt45\Callisto\themes\Generic.xaml
```

App is my main project. Win8-Common is a lib project.

I have not found a way to corretly clean the error

**Comment by timheuer** [comment]
How are you adding a reference.  You must use either the NuGet mechanism or
the Extension SDK.  My suspicion is you are referencing the DLL directly
only?

**Comment by tallichet** [comment]
I used nuget. I used the solution tools that allow to add/remove package for any projects from a global view.

**Comment by timheuer** [comment]
Hmm, can you set up a sample solution that emulates your setup for me?  I
think I may know the issue, but just want to make sure.

**Comment by tallichet** [comment]
I'll try to reproduce it tomorrow

**Comment by tallichet** [comment]
I'm unable to reproduce. But I fixed it in my project by adding Callisto to all my projects. the problem was due to projects using a lib using Callisto but without referencing Callisto themselves.
