### ISSUE TITLE
DirectoryNotFoundException in Appx Package when opening a Flyout

### ISSUE THREAD

**Issue by DGeiss** [timheuer/callisto#153]
Hi,
we receive the following exception when we are opening a flyout in an Appx Package.
The screenshot is from a very simple testapp.

![Exception](https://f.cloud.github.com/assets/2573434/57133/de3252c6-5b3c-11e2-9218-b9c9c64d292a.png)

No exception occurs if we run the app from VS2012 (neither in "Simulator" nor on "Local Machine").

We created the package as described in the following post.
http://peterdn.com/post/To-make-a-Metro-Appx-Package-from-scratch-you-must-first-e280a6.aspx

Thanks in advance.
Gero and Darius

**Comment by timheuer** [comment]
How is it being referenced?  When you create the package is the Callisto
assets (generic.xaml) in the package?

**Comment by DGeiss** [comment]
We added it by Add Referece -> Windows -> Extensions.
The generic.xaml is missing in the unpacked package although its in the
source directory before the packing.

**Comment by DGeiss** [comment]
Sorry we were wrong. The generic.xaml file is in the package!

**Comment by timheuer** [comment]
Hmm, that is interesting (and not expected as it doesn't happen for me).
Can you try the NuGet package reference?

**Comment by DGeiss** [comment]
I switched to the NuGet package, but I still have the same issue.

How we create an appx:
-Build the Solution on our Nightlybuild server
-Use MakeAppx.exe pack /d "ProjectFolder" /p "PackageName.appx"
-Use signtool.exe sign /fd sha256 /sha1 "KeyForCertificate"
"PackageName.appx"

On a developer machine I can always find the Appx folder in Debug or
Release folder, which includes the folder Callisto\Themes\ with the
generic.xaml file.
But on our Nightlybuild server this folder doesn't exist.

An idea what is wrong?

**Comment by timheuer** [comment]
Ah, you are using makeappx directly.  Since you are using this manually and
not MSBuild and the package tasks, then you will need to do what you are
doing.  The VS workflow does all this automatically for you using the PRI
information provided by the controls/references/etc. when packaging to put
the right file dependencies in place.

**Comment by DGeiss** [comment]
We found out that our TFS (NightlyBuild) is making the appx file for us (we just haven't found the file).
This way we don't need to make the package with makeappx.
Sorry for bothering and thank you for your Support.
