### ISSUE TITLE
menu visiblity by default collapsed?

### ISSUE THREAD

**Issue by humbrie** [timheuer/callisto#155]
For one hour i tried to use the flyout menu with simple menuitems, but it simply did not show up. As i set the visibility of the menu to Visible explicitely the menu finally shows up. 

Why is that so? Makes no sense for me...

**Comment by timheuer** [comment]
It is intended to be used within a flyout. Have you seen the use in the docs?

-th

**Comment by humbrie** [comment]
Well, i tried to reconstruct the behavior in my code and removed the line with the visibility and the menu shows up anyway. I dont know why i had the problem before, but in my debug session last week i could see the flyout (marked with a red border) without any content.

tl;dr: sorry, must have been my fault :D
