### ISSUE TITLE
Live tile control not working in a gridview ItemTemplate

### ISSUE THREAD

**Issue by supersume** [timheuer/callisto#157]
I am using the LiveTile control. However, when I include it as part of a DataTemplate in a GridView ItemTemplate, the outer binding for the collection works, but the inner bindings for the controls don't. I have tried to attach loaded event handlers to the LiveTile control and Image as in my code and by using breakpoints, I found out that the LiveTile control binds successfully but the image is never loaded. Replaced the LiveTile with a ListBox and using the same exact code, everything worked perfect. Below is my XAML code

![Capture](https://f.cloud.github.com/assets/3321145/81280/e2244662-630e-11e2-9668-16ac62f4b051.PNG)

**Comment by supersume** [comment]
How do you set up the LiveTile control correctly in a griview ItemTemplate?

**Comment by supersume** [comment]
After digging deep and debugging the LiveTile.cs in my solution, I discovered that the OnApplyTemplate is never called if I put the LiveTile control in a GridView DataTemplate

**Comment by dotMorten** [comment]
I'm using the LiveTile with no problem in a GridView. When you run in debugging, do you see anything in Visual Studio's output window that could hint at some binding issue?
Do you have a more complete repro-sample I can take a look at?

**Comment by supersume** [comment]
That is a XAML page containing a control inherited from Gridview to allow
different sizes of items, that contains the live tiles if the bound item is
of the type 'Subscription'. The Gridview uses a template selector to
determine which template to choose. I copied the LiveTile.cs file into my
project and used it from there when I was having trouble debugging. I have attached the files in the email

**Comment by supersume** [comment]
If you can, please send me a solution file of a project where the live tile is implemented in a gridview. I have tried all options including creating a new project with just a gridview and the LiveTile control in the itemTemplate but failed

**Comment by supersume** [comment]
Problem solved. I was using the compiled dll from the source project. Using the Callisto Nuget package solved the issues

**Comment by dotMorten** [comment]
Sorry I've been a little slow to reply. I'm glad you figured it out. Yes deploying directly from dll can be bit of an issue with WinRT since necessary files can't be embedded no more but must copied to the correct location. The NuGet package takes care of that for you.
