### ISSUE TITLE
Rating : Is there a way to change disabled stars color ?

### ISSUE THREAD

**Issue by RomainNTIC** [timheuer/callisto#158]
Hi, first of all, thanks for this great toolkit who can be very helpfull.

I'm starting to use Rating control in a small project but i've an issue, I can't change stars color when IsEnabled is set to False.

Is there a way to do that without re-design Rating component ? 

Am I using something in a wrong way ? Or it is not possible.

Thanks.

**Comment by timheuer** [comment]
No there is no way to do this without retemplating. The reason is the control follows the UI guidelines/colors from Windows.
