### ISSUE TITLE
Exception when opening Flyout with touch instead of mouse cursor

### ISSUE THREAD

**Issue by rapomax** [timheuer/callisto#161]
When Opening a Flyout as a response to a touch-event on an image ( Image_Tapped(sender, e)) an Unhandled Exception occurs and the app crashes.

Exception: Value does not fall within the expected range.
Message: Failed to get pointer information.

I debugged Fylout.cs but i couldn't find a clear line which causes the exception.

The application is running on Surface RT.
When using the touchpad and clicking the image with the cursor everything works fine.

**Comment by timheuer** [comment]
Can you provide the xaml/code to repro?

**Comment by rapomax** [comment]
This thing drove me crazy. But i finally found the cause and made a project for reproduction.
It seems to have nothing to do with the Flyout itself.
The cause is a programmatical tooltip on the image opening the Flyout which placement was set to PlacementMode.Mouse.
Setting it to Placement.Left works fine with touch.
The strange thing is that i have tooltips with PlacementMode.Mouse on other images too which never caused this error when selecting them with touch. But these images don't open flyouts.
Maybe it has to do with the fact that flyout and tooltip draw into the same region when Placementmode is Mouse.

MainPage.xaml

<Page
    x:Class="Flyout_Repro_Callisto.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:Flyout_Repro_Callisto"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

```
<Grid Background="{StaticResource ApplicationPageBackgroundThemeBrush}">
    <Grid.RowDefinitions>
        <RowDefinition Height="*"/>
        <RowDefinition Height="42"/>
    </Grid.RowDefinitions>
    <Image x:Name="ImageTest" Source="Assets/Touch.png" Grid.Row="1" HorizontalAlignment="Center" VerticalAlignment="Center" CacheMode="BitmapCache" Tapped="ImageTest_Tapped"/>
</Grid>
```

</Page>

using Callisto.Controls;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Windows.Foundation;
using Windows.Foundation.Collections;
using Windows.UI.Xaml;
using Windows.UI.Xaml.Controls;
using Windows.UI.Xaml.Controls.Primitives;
using Windows.UI.Xaml.Data;
using Windows.UI.Xaml.Input;
using Windows.UI.Xaml.Media;
using Windows.UI.Xaml.Navigation;

namespace Flyout_Repro_Callisto
{
    /// <summary>


    /// </summary>


    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            this.InitializeComponent();

```
        this.Loaded += MainPage_Loaded;
    }

    void MainPage_Loaded(object sender, RoutedEventArgs e)
    {
        ToolTip tt = new ToolTip();

        tt.Content = "Test Tooltip";
        ToolTipService.SetToolTip(ImageTest, tt);

        //This causes the error. Changing it to  PlacementMode.Left works.
        ToolTipService.SetPlacement(ImageTest, PlacementMode.Mouse);
    }

    private void ImageTest_Tapped(object sender, TappedRoutedEventArgs e)
    {
        Flyout flyOut = new Flyout();

        flyOut.Placement = PlacementMode.Top;
        flyOut.PlacementTarget = sender as UIElement;

        ListBox lb = new ListBox();

        lb.Items.Add("Item 1");
        lb.Items.Add("Item 2");
        lb.Items.Add("Item 3");
        lb.Items.Add("Item 4");
        lb.Items.Add("Item 5");

        flyOut.Content = lb;
        flyOut.IsOpen = true;
    }
```

**Comment by timheuer** [comment]
Using the exact code above on my Surface I could not repro.

**Comment by rikkit** [comment]
Just got a NotImplemented exception when using PlacementMode.Mouse... seems related.

```
private void OnStoryClick(object sender, ItemClickEventArgs e)
        {
        _storyDetailCard = new DetailCard();

        var story = e.ClickedItem as ZenStory;

        if (story == null)
        {
            return;
        }

        var details = new Flyout
                          {
                              Height = 400,
                              Width = 600,
                              Placement = PlacementMode.Mouse,
                              PlacementTarget = (UIElement) sender
                          };

        _storyDetailCard.DataContext = story;

        details.Content = _storyDetailCard;

        details.IsOpen = true;
    }
```

The exception:

System.NotImplementedException
   at Callisto.Controls.Flyout.PerformPlacement(Double horizontalOffset, Double verticalOffset)
   at Callisto.Controls.Flyout.OnHostPopupOpened(Object sender, Object e)

The placement target is an item in a vertical listview, which is part of a series of listviews, all wrapped in a scrollviewer. OnStoryClick is called on ListView.ItemClick.

**Comment by timheuer** [comment]
Yes, @rikkit PlacementMode.Mouse is not supported for Flyouts.
