### ISSUE TITLE
Adding pictures in flyout menus

### ISSUE THREAD

**Issue by rradi** [timheuer/callisto#163]
Is it possible to add a additional feature to flyout menus, allowing one to add pictures to items in flyout menus to achieve the result shown in the attached mockup for example?

![2013-02-19_110442](https://f.cloud.github.com/assets/3635506/170845/559eee94-7a7f-11e2-9761-47595c1578c5.png)

**Comment by timheuer** [comment]
You could re-template the item

**Comment by rradi** [comment]
Hi Tim, sorry to bother you, but can i ask you to explain a bit more how to do that? thank you in advance

**Comment by timheuer** [comment]
You would have to re-template the MenuItem style and add the template part
you would need.  Perhaps even sub-class as needed the control.
