### ISSUE TITLE
Adding pictures in flyout menus

### ISSUE THREAD

**Issue by rradi** [timheuer/callisto#164]
Is it possible to add a additional feature to flyout menus, allowing one to add pictures to items in flyout menus to achieve the result shown in the attached mockup for example?

![2013-02-19_110442](https://f.cloud.github.com/assets/3635506/170850/a2dae992-7a7f-11e2-9d52-ec8cb7043d36.png)

**Comment by timheuer** [comment]
You'd have to re-template the MenuItem control template.
