### ISSUE TITLE
Bind Style to DynamicTextBlock

### ISSUE THREAD

**Issue by Ponf** [timheuer/callisto#165]
I found some problem with binding custom styles to DynamicTextBlock:
I have created DependencyProperty TextblockStyle and event OnTextblockStyleChanged. In this event I am making something like this:

(DynamicTextBlock)d.textBlock.Style = TextblockStyle.

But I have crash at NotifyPropertyChanged on this element. Style can be changed during application execution, so apply style in constructor is not very good idea, I think.

Styles are made in this way:
            <Style x:Key="BaseDynamicTextBlockStyle" TargetType="controls:DynamicTextBlock">
                <Setter Property="FontFamily" Value="Segoe UI"/>
                <Setter Property="FontWeight" Value="SemiLight"/>
                <Setter Property="FontSize" Value="17.33"/>
                <Setter Property="Foreground" Value="#000000"/>
            </Style>
            <Style x:Key="BoldSubjectTextBlockStyle" TargetType="controls:DynamicTextBlock" BasedOn="{StaticResource BaseDynamicTextBlockStyle}">
                <Setter Property="FontFamily" Value="Segoe UI"/>
                <Setter Property="FontWeight" Value="SemiBold"/>
                <Setter Property="Foreground" Value="#000000"/>
            </Style>

**Comment by timheuer** [comment]
can you provide a repro project with the style you are using?

**Comment by Ponf** [comment]
Sure. I have fixed that problem with styles creating generic.xaml for this DynamicTextBlock and with little changes in code-behind. But now I have problem with TextWrapping :(
Sample project on SkyDrive: http://sdrv.ms/VvnVpI

**Comment by Ponf** [comment]
I fixed this problem:
we need to comment           

//this.textBlock.TextWrapping = (TextWrapping)e.NewValue;

because textwrapping passed from generic.xaml using binding :)
So, everything is clear, thanks!

**Comment by timheuer** [comment]
@Ponf what is meant by your last comment of why you needed to comment that out?

**Comment by Ponf** [comment]
Because I have made binding in generic xaml:  
TextWrapping="{Binding TextWrapping, RelativeSource={RelativeSource TemplatedParent}}"

And I have made Template binding for other properties to easily apply styling:
FontStyle="{TemplateBinding FontStyle}"

Ready version of my sample with support of styling and IsTextSelectionEnabled property:
http://sdrv.ms/VvnVpI

**Comment by timheuer** [comment]
Closing as it appears to have been an app issue
