### ISSUE TITLE
When a Menu is wrapped in a UserControl which is added to a Flyout, the app crashes when hitting Escape

### ISSUE THREAD

**Issue by areijngoudt** [timheuer/callisto#166]
The Menu.OnKeyDown expects the parent to be a Flyout:
private void OnKeyDown(object sender, KeyRoutedEventArgs args)
        {
            switch (args.Key)
            {
                case Windows.System.VirtualKey.Escape:
                    ((Flyout)this.Parent).IsOpen = false;
                    break;
When the Menu is wrapped in a UserControl, the Cast fails when [Escape] is pressed, and the app is terminated

**Comment by stefanolson** [comment]
Duplicate of: https://github.com/timheuer/callisto/issues/140
