### ISSUE TITLE
Problem with CustomDialog

### ISSUE THREAD

**Issue by marcominerva** [timheuer/callisto#168]
I have an Issue with CustomDialog control. I'm trying the Callisto TestApp. If I show the Custom Dialog and then snap the app, the dialog doesn't auto-size: the text doesn't wrap and I can't see the buttons. Here is a screenshot:

![0ceeb4a4-7327-11e2-95cb-2f90f67b79ea](https://f.cloud.github.com/assets/3522534/180851/6b9c0332-7c3f-11e2-9366-6ae8fdf531f2.png)

**Comment by timheuer** [comment]
Dupe of #147
