### ISSUE TITLE
How to decrease height  and width of rating control

### ISSUE THREAD

**Issue by rohit499** [timheuer/callisto#169]
How to decrease height  and width of stars in rating control

as when i do it with height and width it does not decrease height and width of full control but i want that if i decrease height and width of rating control relatively stars height and width get adjusted

**Comment by dotMorten** [comment]
Can't you just put a ViewBox around it, then instead set the desired size on the ViewBox?

**Comment by andrejt** [comment]
Change font size?

**Comment by rohit499** [comment]
Thanks andrejt and dotMortem for a quick reply....

i tried second one and it is working

**Comment by timheuer** [comment]
Do you want to change the size of the stars?  FontSize should do that (odd I know, but that is how it is mapped)
