### ISSUE TITLE
SettingsFlyout

### ISSUE THREAD

**Issue by GIORGIOSF** [timheuer/callisto#170]
I tried SettingsFlyout from Callisto ver. 1.2.6 with the following code:

```
        // Add an About command
        var about = new SettingsCommand("about", "About", (handler) =>
        {
            var settings = new SettingsFlyout();
            settings.Content = new AboutUserControl();
            settings.HeaderBrush = new SolidColorBrush(_background);
            settings.Background = new SolidColorBrush(_background);
            settings.HeaderText = "About";
            settings.IsOpen = true;
        });

        args.Request.ApplicationCommands.Add(about);
```

settings.HeaderBrush works fine (I tried with different colours)

settings.Background is ignored: the background is always white

**Comment by timheuer** [comment]
This is by-design.  The background per UX guidelines is always "light" themed.  I've added an override in ContentBackground property.

**Comment by GIORGIOSF** [comment]
So, when I insert e.g. a ToggleSwitch, it remains invisible because the framework draws it white; changing the foreground and border for it does not work; applying RequestedTheme="Light" is not supported for the page only - should I change it for the whole app?

**Comment by timheuer** [comment]
If you have a dark-themed app, then you'd either a) re-style the control
for use in the default settings flyout (preferred) or b) change the
ContentBackground property of the flyout to a dark color (not preferred as
it doesn't adhere to ideal UI guidelines)

-th

---

http://timheuer.com/blog/
twitter: @timheuer

**Comment by GIORGIOSF** [comment]
Thank you.

Indeed, I was already thinking about solution (a) - but of course it requires a lot of work if one has several types of controls in the flyout.

Sent from Windows Mail

From: Tim Heuer
Sent: ‎March‎ ‎18‎, ‎2013 ‎3‎:‎22‎ ‎PM
To: timheuer/callisto
CC: GIORGIOSF
Subject: Re: [callisto] SettingsFlyout (#170)

If you have a dark-themed app, then you'd either a) re-style the control 
for use in the default settings flyout (preferred) or b) change the 
ContentBackground property of the flyout to a dark color (not preferred as 
it doesn't adhere to ideal UI guidelines) 

-th 

---

http://timheuer.com/blog/ 
twitter: @timheuer
