### ISSUE TITLE
Issue with Callisto in VS2012 Professional

### ISSUE THREAD

**Issue by emmawilson** [timheuer/callisto#172]
While using the Callisto extension, I am able to create objects but they seem to be invisible(their boundary cannot be modified). They just blend into the background. I tried changing the background color, border thickness but that also doesn't help.

**Comment by timheuer** [comment]
What control?  This sounds like a theme issue.  If the Settings/Flyout controls you would have to provide styles for anything you put in there to ensure you aren't running into a light/dark theme conflict.  SettingsFlyout has a ContentBackground property you can set.
