### ISSUE TITLE
Is it possible to change the CustomDialog's content width?

### ISSUE THREAD

**Issue by tonyyineseelynx** [timheuer/callisto#179]
Is there any way to change the CustomDialog's content width? For instance, make it 98% of the CustomDialog's total width. The default content width (about 600-700) is too short for my app.  Any helps? Thanks.

By the way, I am using Callisto 1.2.6 from NuGet.

**Comment by timheuer** [comment]
I try to match our UI guidelines specifically to ensure that if a proper control ever came along, that it wouldn't impact developers negatively.  Right now the max width of 680px is the design guideline.  For now, I won't be changing this.
