### ISSUE TITLE
Settings fly-out displayed underneath the other controls.

### ISSUE THREAD

**Issue by BrianDT** [timheuer/callisto#187]
![settings flyout issue](https://f.cloud.github.com/assets/4189260/395511/8aaf16cc-a801-11e2-84bd-2cdd239b3838.png)
![permissions flyout OK](https://f.cloud.github.com/assets/4189260/395513/8f3bd6e4-a801-11e2-983d-2f73e30f3b69.png)

The first attached image shows a fly-out under a WebView control, this does not happen to the system generated permissions fly-out as show in the second attached image.

**Comment by timheuer** [comment]
This is actually a WebView issue. WebView owns the z-index order. If something might show over it as in your case you need to switch to a WebViewBrush temporarily. 

Not something Callisto can solve.

**Comment by BrianDT** [comment]
Thanks for the hint about the WebViewBrush, that worked well.
