### ISSUE TITLE
en-za localization support?

### ISSUE THREAD

**Issue by csmaster2005** [timheuer/callisto#189]
Hi,
I have a customer who was reporting a crash, and upon further investigation I found that the customer has their local set to South African english (en-ZA), which callisto doesnt support, and was most likely causing the crash.
1. Can en-ZA support please be added? From having him glance over the en-US resources, the same strings should suffice.
2. I would do this myself and submit a pull request, but wasnt sure what was needed - I tried just creating an en-za folder with the same resources, but that still resulted in the crash, so I'm not sure what other steps I'd need to take to 'add support' for the language in the lib.
3. Is expected behavior for Callisto to crash for unsupported locals? Or is there supposed to be a graceful fallback that I may of perhaps broken?

Thanks

**Comment by timheuer** [comment]
It should be falling back to the default language for the app...however I assume that is en-ZA for your app :-).  in that case it should still follow the flow back and choose closest which would be "en" -- however that isn't present.  This is a good bug.

Can you confirm the resources for en-US would suffice?

**Comment by csmaster2005** [comment]
Actually, my app is in en-us. I really dont know much about localization, so which I could help more. Not sure why/if it isnt actually falling back to callisto's en-us? Or are you saying it would try to fall back to en, which isnt there anyways?

And yes, I just asked the customer and he said the en-us resources should suffice. Better than nothing? ;)
