### ISSUE TITLE
Stop SettingsFlyout from closing when opening FilePicker or FolderPicker?

### ISSUE THREAD

**Issue by MJTSoftware** [timheuer/callisto#191]
I've got a FolderPicker on my SettingsFlyout. I was wondering if we can prevent the SettingsFlyout from closing when the FolderPicker comes up on the screen.

Right now I'm trying to monitor the Closed event so if someone adds a directory I can update the UI outside the SettingsFlyout. Now it is firing the Closed event right when my FolderPicker pops up on the screen.

Let me know if I need to explain further.

Thanks!

**Comment by timheuer** [comment]
Unfortunately no.  The guidelines for the flyouts are that when the window isn't active it dismisses.  I can see this as an interesting case though (I assume the picker is for some type of avatar or profile image of sorts).  However, this wouldn't be something that I'd want to build into the control right now as it doesn't match with the guidelines of the platform.
