### ISSUE TITLE
Flyout appears below ad

### ISSUE THREAD

**Issue by aschearer** [timheuer/callisto#199]
I have a Live SDK AdControl on the right-hand side of the screen. When I open the settings page hosted using Callisto's flyout the page appears below the ad.

**Comment by dotMorten** [comment]
This is a known airspace issue with the ad SDK. Try calling .Suspend() on the ad control when the fly out opens, and .Resume() when it closes again.

**Comment by aschearer** [comment]
Thanks for the follow up. I've simply moved the ad to the left hand side for now but will keep your recommendation in mind. Sounds like the bug is with the ad SDK.
