### ISSUE TITLE
CustomDialog doesn't appear after run it

### ISSUE THREAD

**Issue by sunco007** [timheuer/callisto#202]
I just download the Callisto TestApp and on the code I set the CustomDialog to IsOpen="True" so I can see it and made some changes/study how it works

Then, I run the Project and closes it. When go to Visual Studio you can't see the CustomDialog anymore. You need to change the True to False and then again to True

I'm using 1.2.9 version and VS Express 2012 for Windows 8

**Comment by timheuer** [comment]
I don't fully understand here?  are you talking about the design surface within VS?

**Comment by sunco007** [comment]
My repro steps
- Open the TestApp
- Go to CustomDialog and add IsOpen="True"
- You can see the dialog
- Run the Project
- Stop the Project

Now you can't see the dialog
- Change IsOpen to False
- Change IsOpen to True

You can see it again

**Comment by timheuer** [comment]
Got it. Another design time issue. I am not sure what I can do here but the designer doesn't appear to be responding.   The control works at runtime by design though.
