### ISSUE TITLE
CustomDialog and Zoom view in VS

### ISSUE THREAD

**Issue by sunco007** [timheuer/callisto#203]
Using the Callisto TestApp I want to change some elements to the CustomDialog part. So I set the IsOpen to True. Then adjust the Zoom of the design mode but the CustomDialog still the same size

Also when trying to scroll the default bars is having an issue

I'm using 1.2.9 and VS Express 2012 for Windows 8

Screenshot attached

![cd](https://f.cloud.github.com/assets/622200/523454/380afe1e-c0ba-11e2-8d6f-8979337d8321.png)

**Comment by timheuer** [comment]
Unfortunately looks like a tools bug.

**Comment by sunco007** [comment]
Is there a way to detect the zoom or scroll so we can update/refresh ? Something like OnResize on a user control

**Comment by timheuer** [comment]
I haven't done any design-time specific code in any if the controls and trying to minimize the surface area. This is likely an issue with the design surface and coordinating window bounds.
