### ISSUE TITLE
Flyout should hide on orientation change

### ISSUE THREAD

**Issue by stefanolson** [timheuer/callisto#206]
The flyout doesn't move when you change orientation from landscape to portrait and the therefore can appear in an unexpected place, or if you move from portrait to landscape it can disappear completely.

I wonder if the best thing to do is just to hide it when the orientation changes.  I have done this and can provide code if you wish.

**Comment by timheuer** [comment]
@stefanolson this should be happening already.  Are you on the latest version.  An orientation triggers a Window size changed event and the Flyout code is set to close the flyout when that occurs.
