### ISSUE TITLE
No Way to Dismiss open Flyout

### ISSUE THREAD

**Issue by KevinAnthony** [timheuer/callisto#209]
When Attaching a Menu to a Flyout, there is no way to dismiss the flyout when the user selected one of the menu items.  
flyout.IsOpen = false;
flyout.Dispose();
flyout.Visibility = Visibility.Collapsed;
flyout = null;
flyout.width = 0; flyout.height = 0;
someotherbutton.Focus(...);

None of those work

**Comment by timheuer** [comment]
Can you provide a snippet.  The test app does this and dismisses just fine.  When you select an item in the menu (assuming you have either a command or Tapped event being handled) it should do this (and does in the sample app)
