### ISSUE TITLE
Flyout needs to be touch keyboard aware

### ISSUE THREAD

**Issue by longzheng** [timheuer/callisto#21]
If Flyout contains a textbox, it will not update position when the touch keyboard slides out

Here is a sample I found that has some basic repositioning logic
http://snatz.ioix.net/data/news/view/14315138866459610847-12-03

**Comment by timheuer** [comment]
Yes this is an issue with a non-rooted Popup.  If you root the flyout to something in the visual tree, it will be treated like other input and scroll into view.  By default the Flyout base isn't rooted, so that is the problem.

**Comment by longzheng** [comment]
Can you root it to the page?

**Comment by timheuer** [comment]
yep just anywhere in the visual tree should adjust

---

http://timheuer.com/blog/
twitter: @timheuer

On Sun, Apr 29, 2012 at 10:52 PM, Long Zheng <
reply@reply.github.com
