### ISSUE TITLE
MenuItem's Command is not activated by keyboard

### ISSUE THREAD

**Issue by robertos** [timheuer/callisto#210]
When a MenuItem with a Command is added to a Menu and the user can navigate to it using the keyboard (e.g. open AppBar with Win+Z, Tab to button, Enter), the options can be selected with the keyboard but Enter or Space do not activate the menu item's Command.

Expected: Enter or Space key would activate the menu item's Command.

**Comment by timheuer** [comment]
Dupe of #84
