### ISSUE TITLE
Weird Flyout behavior

### ISSUE THREAD

**Issue by hermitdave** [timheuer/callisto#212]
Hi,

I have a xaml page that I load using flyout. The flyout has two buttons in addition to textboxes etc. The larger of the textboxes allows 140 char entry and I have tried various combinations like setting height and making scrollbars visible to try and work around however the flyout after cursor comes to full width of textbox just jumps out. 

Infact I have seen flyout jumping all over the place, vibrating
Here's a link to screencast
http://t.co/fZKARfdtEd

**Comment by timheuer** [comment]
Well this certainly is weird.  Any chance you can isolate to a repro I can look at...using the same structure that is in your flyout with any relevant events or anything?

**Comment by hermitdave** [comment]
let me do that :)

**Comment by hermitdave** [comment]
Tim,

After playing with Flyout, I modified the code to use Popup and based on popup's behaviour, I set the width for content grid and the text to wrap

This mean that popup was working. Having switched to using flyout again with same this behaviour cannot be replicated (however removing the text wrapping brings it back)

Do you want me to give you a repro for the issue anyways ?

**Comment by timheuer** [comment]
Yes there is something in your content that is conflicting with others…I want to replicate the same thing

Sent from Windows Mail

From: hermitdave
Sent: ‎Friday‎, ‎June‎ ‎21‎, ‎2013 ‎7‎:‎22‎ ‎AM
To: timheuer/callisto
Cc: Tim Heuer

Tim,

After playing with Flyout, I modified the code to use Popup and based on popup's behaviour, I set the width for content grid. 

This mean that popup was working. Having switched to using flyout again with same (fixed width content), this does not happen. 

Do you want me to give you a repro for the issue anyways ?

**Comment by hermitdave** [comment]
Tim,

You can download the repro here http://sdrv.ms/11RYxKC 

the work around in this case is setting the Text to wrap.

Hermit
