### ISSUE TITLE
Callisto 1.3.1 with .net 4.5 framework issue

### ISSUE THREAD

**Issue by JoeyKent** [timheuer/callisto#215]
Hi,

I am developing a WPF application using .net 4.5 framework. I tried installing Callisto 1.3.1 using Nuget but I received the following error

Install-Package : Could not install package 'Callisto 1.3.1'. You are trying to install this package into a project that targets '.NETFra
mework,Version=v4.5', but the package does not contain any assembly references that are compatible with that framework. For more informat
ion, contact the package author.
At line:1 char:16
- Install-Package <<<<  Callisto
  - CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

How can I use Callisto with .net 4.5 ?

**Comment by sascha-andres** [comment]
Hi,

Callisto is meant to be used for WindowsStore apps. That means you can use along with the the project templates listed under the node Windows Store but not with projects listed under Windows. If your output type is Windows application (properties of your project), then the error is expected.

**Comment by JoeyKent** [comment]
Is there live tile control available for WPF ? Thanks.

**Comment by dotMorten** [comment]
No it is not, but I don't see too much stuff in there that would make it hard to port to WPF. Pull the source and template in and change a few namespaces and it'll probably work.

**Comment by JoeyKent** [comment]
Hello dotMorten,

I tried modifying the below files for WPF https://github.com/timheuer/callisto/blob/master/src/Callisto.TestApp/SamplePages/LiveTileSample.xaml
and 
https://github.com/timheuer/callisto/blob/master/src/Callisto.TestApp/SamplePages/LiveTileSample.xaml.cs

The solution builds but nothing is displayed on the window using Livetile. Am I missing anything ?

**Comment by JoeyKent** [comment]
I created a new solution with the 2 files (LiveTiveSample.xaml.cs and LiveTileSampe.xaml.
The solution builds fine but OnApplyTemplate() of LiveTile.cs is not called. Can you please tell me the reason ?

**Comment by dotMorten** [comment]
Did you remember to add the template to Themes\Generic.xaml

**Comment by JoeyKent** [comment]
I tried adding the file but couldn't succeed. Can you provide a sample WPF solution for LiveTile control ?

**Comment by dotMorten** [comment]
I'm away from my PC all weekend so can't do it now. You only need to include the live tile template and it will need a little tweaking to make it wpf compatible.

**Comment by JoeyKent** [comment]
Added Generic.xaml to Themes folder and added the live tile template. I am getting the below error in Generic.xaml.

Error   1   The tag 'ResourceDictionary.ThemeDictionaries' does not exist in XML namespace 'http://schemas.microsoft.com/winfx/2006/xaml/presentation'.

**Comment by sascha-andres** [comment]
Not much time currently, but I once read a blog here: http://www.sourceblog.mc-auto.info/post/2011/11/23/Live-Icons-in-WPF.aspx There are component vendors out there that include tile controls ion their packages (component one and DevExpress for example)

**Comment by JoeyKent** [comment]
Hi dotMorten, I tried making it WPF compatibe but couldn't succeed. Can you please provide a sample solution ?
