### ISSUE TITLE
Null object reference error setting isopen property to  true when PlacementTarget property is not set

### ISSUE THREAD

**Issue by rprakashg** [timheuer/callisto#226]
I noticed an issue with Flyout control; if you don't set the PlacementTarget property and set IsOpen to true, throws a null object reference error

**Comment by timheuer** [comment]
By design.  The Flyout needs to know where it originates from.

**Comment by rprakashg** [comment]
Sure how about adding a constructor that takes PlacementTarget as parameter since its required for Flyout, this way will be forced to specify

**Comment by timheuer** [comment]
That or make the exception better :-)

---

http://timheuer.com/blog/
twitter: @timheuer

**Comment by rprakashg** [comment]
That would be good too :) Awesome toolkit BTW
