### ISSUE TITLE
WatermarkTextbox doesn't work in Blend designer

### ISSUE THREAD

**Issue by xperiandri** [timheuer/callisto#227]
ResourceMap not found
 at Windows.ApplicationModel.Resources.ResourceLoader..ctor(String name)
 at Callisto.Controls.WatermarkTextBox..ctor()

Used Blend 2013 RC

**Comment by timheuer** [comment]
I am not seeing this.  I see the default when I type

```
<callisto:WatermarkTextBox xmlns:callisto="using:Callisto.Controls" Width="300" Height="35" />
```

This is using Blend 2012 with Update 3 applied.

**Comment by xperiandri** [comment]
I have written that problem occurs in Blend 2013!

**Comment by timheuer** [comment]
I still cannot reproduce this, however it could be an problem with the RC build of 2013 (I am running a later build for RTM).  However, WatermarkTextBox is obsolete in 2013 (assume you are building an 8.1 app) as you can use PlaceholderText on TextBox itself now and no longer need this control.

**Comment by xperiandri** [comment]
No, actually I was building 8.0 app
Just opened in 2013

**Comment by timheuer** [comment]
Hmm, that isn't really supported as 2013 targets 8.1 -- you should have got a warning about that.  This is likely the cause.  I'm not seeing the error on a Win8 app using Blend 2012 (which is supported) and using it on an 8.1 project I don't see it as well.  You are using a tool targeting 8.1 apps for an 8.0 project (and actually should have been blocked)

**Comment by xperiandri** [comment]
Not so. They declare support of 8.0 projects in 2013 products

**Comment by timheuer** [comment]
Interesting, didn't think we supported that :-) -- regardless in the RTM builds I still don't see it even in that scenario.  Could be just a preview bug.
