### ISSUE TITLE
Controls no longer visible in Designer

### ISSUE THREAD

**Issue by ghost** [timheuer/callisto#238]
Hi there,

I started using Callisto and it worked fine. Then I upgraded from VS2012 to VS2013 and after a while the controls are no longer displayed in the designer. I can still use everything and when I run the App, it works fine.
Only when editing I just see the frame but no longer the control inside and also in the toolbox, instead of the small icon there is just "<>".
Is this expected behaviour or am I missing some configuration. The installation was done via NuGet.

Best Regards

Phil

**Comment by timheuer** [comment]
This is an issue with nuget packages where designer information not well supported. Sorry
