### ISSUE TITLE
[feature need]when will support C++/cx ?

### ISSUE THREAD

**Issue by tfzxyinhao** [timheuer/callisto#239]
This project is great,but when will support c++/cx?

**Comment by timheuer** [comment]
Thanks for the compliment @tfzxyinhao however there are no plans for a native port at this time.  The main reason is that I've had very little requests for it and the current code makes great use of C# language features not present in C++ which would require more thinking on my part.

However, it is permissively licensed and feel free to download the XAML code and use at your will!  There was an earlier C++/Cx port but it hasn't evolved and isn't complete.
