### ISSUE TITLE
CustomDialog Styling

### ISSUE THREAD

**Issue by JoshClose** [timheuer/callisto#242]
Is there an easy way to style stuff inside the CustomDialog? If I have a button inside the default white CustomDialog, the button isn't visible until I click on it. I'd rather not have to change the visual states of the button for this.

**Comment by timheuer** [comment]
Are you on Windows 8.1?  If so, change the RequestedTheme on the dialog.

---

http://timheuer.com/blog/
twitter: @timheuer

**Comment by JoshClose** [comment]
I am. If I change it to `Light` instead, I get a black dialog. The theme I'm using is dark, so having a white popup is better. 

Doing `RequestedTheme="Light" Background="White"` gives me the same white background, but I can see the controls. Is this what you are suggesting?

Btw, thanks for creating Callisto! I've found it very useful.

**Comment by timheuer** [comment]
I see.  You'll have to set RequestedTheme on the button to light then in
this case.  It is getting the default theme (dark) and drawing it as such.

---

http://timheuer.com/blog/
twitter: @timheuer

**Comment by JoshClose** [comment]
Thanks Tim!
