### ISSUE TITLE
Rating : Can I use other symbol instead of "Star" ?

### ISSUE THREAD

**Issue by AbdShak** [timheuer/callisto#247]
can i used "$" for rate something instead of star using the same control ? 

Thank you,

**Comment by timheuer** [comment]
Yes, use the Tag property -- see example in test app: https://github.com/timheuer/callisto/blob/master/src/Callisto.TestApp/SamplePages/RatingControl.xaml

**Comment by AbdShak** [comment]
Thank you TIm , you are the best !

using Tag=&# x1f4b2; for $
