### ISSUE TITLE
Unable to install this extension.

### ISSUE THREAD

**Issue by Forro-54** [timheuer/callisto#254]
Hi Tim,
I am trying to install this extension on a windows 8.1 machine so I can follow Bob Tabors series on windows store apps but unfortunately when I try to install it I get a message that it is targeted to DotNet Frame work 4.

I have vs 2012 sp4 installed and this is the version I am trying to use for the project, ContosoCookbook!  I have tried installing the version from the vs gallery and the locked version.

btw: I also have vs 2013 installed on the same machine.

When I go to project properties and try and change the framework version from 4.5 to 4 the Target Framework Drop down is greyed out.

I appreciate that you are probably busy but do you have any idea how to get around this.

Kind Regards
Trevor
![callisto2](https://cloud.githubusercontent.com/assets/7608527/5213479/53188186-7662-11e4-9e67-d812aec86c5d.gif)

**Comment by timheuer** [comment]
You indicate you are unable to install this, but you aren't showing an install failure dialog.  You must first install the toolkit either via the Extension SDK or the NuGet package.  Which one of those have you done?

**Comment by Forro-54** [comment]
Hi Tim,

Thank you for taking the time to reply.

I was able to eventually resolve this problem by installing callisto via nuget command line as opposed to the method used by Bob Tabor.

However, I really appreciate your reply.

Kind Regards

Trevor

---

Trevor Forrester

Phone: 0267608100

Mobile: 0409398350

Email:  mailto:trevor@forrestitservices.org trevor@forrestitservices.org

Web URL:  http://forrestitservices.org/ http://forrestitservices.org
