### ISSUE TITLE
Morten: Please add GZipWebClient

### ISSUE THREAD

**Issue by aaronwro** [timheuer/callisto#28]
enough said.

**Comment by dotMorten** [comment]
What do you mean? WinRT has GZip/Deflate built into the HttpClient. Just declare it this way:
HttpClient client = new HttpClient(new HttpClientHandler() { AutomaticDecompression = DecompressionMethods.Deflate | DecompressionMethods.GZip });

**Comment by aaronwro** [comment]
I didn't know that, thanks!
