### ISSUE TITLE
Complete Date/Time picker controls

### ISSUE THREAD

**Issue by timheuer** [timheuer/callisto#3]
Implement date/time pickers using Globalization calendar information.

**Comment by lambda125** [comment]
Hi Tim,
I have created a date time picker for Metro XAML which I'm using in my app. Would you like to start with that control and improve it?

Regards,
Krishna

**Comment by timheuer** [comment]
Hey Krishna!  Would love to see the starting point to ensure it conforms to the OS pickers. 

-th

**Comment by lambda125** [comment]
Hi Tim,

Not sure if it will conform to the OS pickers - it was something quick for my app really. I've included the source code here. And a couple of screenshots.

https://skydrive.live.com/redir.aspx?cid=3e3feb178630aaef&resid=3E3FEB178630AAEF!284&parid=3E3FEB178630AAEF!276

cheers 
-K
