### ISSUE TITLE
Settings Flyout Template issues

### ISSUE THREAD

**Issue by stefanolson** [timheuer/callisto#31]
Grid containing the actual settings panel content should have a vertical alignment of Stretch, rather than top.
The template uses a ContentControl rather than a ContentPresenter.

**Comment by AButler** [comment]
@timheuer 

The Grid that contains the ContentPresenter still has a HorizontalAlignment="Left" which makes placing controls that are full width in the SettingsFlyout a bit tricky. Can I suggest this is changed to HorizontalAlignment="Stretch" or even HorizontalAlignment="{TemplateBinding HorizontalContentAlignment}"?
