### ISSUE TITLE
Notify when SettingsFlyout closed

### ISSUE THREAD

**Issue by stefanolson** [timheuer/callisto#33]
Please implement a Closed handler on SettingsFlyout, so that I can be notified when it shuts.  There are a number of settings that the user might set that will cause me to refresh the page. I don't want to do that until the user has completed the settings, otherwise it could waste a lot of data, so I need to know when the fly out is shut, and refresh then. Would be fine if it worked the same way as Flyout does, I think.

**Comment by timheuer** [comment]
This should be the same as how flyout works.  Also, the Win8 guidelines are
such that settings are immediate, not when a settings dialog is closed (in
fact no 'save/close' buttons are suggested).

-th

---

http://timheuer.com/blog/
twitter: @timheuer

On Fri, May 18, 2012 at 9:50 PM, stefanolson <
reply@reply.github.com

**Comment by stefanolson** [comment]
Yes, it should be the same as how Flyout works. Flyout has a Closed event, SettingsFlyout does not.  

I am definitely aware of the UI guidelines, and the settings are saved immediately, it's just that I don't want to update the UI, which is currently displayed, in case the user changes their mind.  If they change a setting and it downloads 300 or 400 K of data, (a huge amount on New Zealand 3G pricing) and then change their mind and go back to the original setting of only downloading on an unlimited plan, then they have wasted money.  I put the guideline of avoiding wasting network traffic ahead of the guideline of immediate updating.

**Comment by timheuer** [comment]
cool, makes sense (hopefully you are aware of the WinRT APIs to assist in
metered networks).  I thought I mirrored the model after Flyout...we'll
expose the Closed event.

---

http://timheuer.com/blog/
twitter: @timheuer

On Sun, May 20, 2012 at 1:28 PM, stefanolson <
reply@reply.github.com

**Comment by stefanolson** [comment]
Thanks - that would be good.

Yes, I think I'm aware of the correct Apis - I use if (NetworkInformation.GetInternetConnectionProfile().GetConnectionCost().NetworkCostType == NetworkCostType.Unrestricted) to check if it is unlimited.  

...Stefan
