### ISSUE TITLE
Back button doesn't always have a hover color

### ISSUE THREAD

**Issue by stefanolson** [timheuer/callisto#35]
If you run the sample application with a dark theme, the back button in the settings fly out no longer has a hover color.  You do get one in the light theme.  I'm not clear why this isn't working, as it should be pulling the BackButtonHoverBackgroundBrush from the current theme, as far as I can tell.  Pressed color works though.

....Stefan

**Comment by timheuer** [comment]
This has been fixed in an updated release version
