### ISSUE TITLE
Flyout dimensions limited

### ISSUE THREAD

**Issue by DreamTimerZ** [timheuer/callisto#36]
It seems that I can't make a Flyout bigger than Width=450 or so.  Is this by design or is there someway I can make it bigger?
I tried specifying the width of my user control at construction time but it still did no good, the controls were cut off on the right hand edge.

**Comment by timheuer** [comment]
By design per ux guidelines from windows

-th

**Comment by DreamTimerZ** [comment]
Thanks for the quick feedback.  There's so many new UX guidelines!  I guess this makes sense if one considers split view and portrait orientations.
