### ISSUE TITLE
OAuthTools.GetSignature method throws NotImplementedException

### ISSUE THREAD

**Issue by chrischiaro** [timheuer/callisto#44]
In OAuthTools.cs, line 310 (inside the final GetSignature overload) throws a NotImplementedException because it passes “HMAC_SHA1” into the OpenAlgorithm method. According to the documentation on MSDN "HMAC_SHA1" isn’t a valid value.

Since the algorithm provider class instantiated inside the method is only used to specify which provider implementation should be used in your HashWith extension method (Extensions.cs, line 414), perhaps a better implementation would be to just translate the OAuthSignatureMethod enum value into a string and pass that into the HashWith method. As long as the “HMAC_SHA1” string gets passed into the MacAlgorithmProvider.OpenAlgorithm method, things work fine.

**Comment by timheuer** [comment]
Fixed in latest code and 1.0.6 release
