### ISSUE TITLE
Settings flyout and layout changes

### ISSUE THREAD

**Issue by sethcrichton** [timheuer/callisto#46]
I haven't tested this in all cases, but setting _windowBounds in the constructor of the control and then using it in the loaded event to set Canvas.LeftProperty doesn't allow reaction to changes in the layout.  If the view loads in fullscreen mode, and then is changed to filled, the settings flyout will render too far to the right by 320 pixels.

**Comment by timheuer** [comment]
Good bug. I'll add listening to window size events to determine if it should even display (ie snapped)

-th

**Comment by timheuer** [comment]
Actually Seth, this shouldn't be the case.  If the view launches in full screen mode, all is well.  The action of a user getting an app to Fill mode, then the window is de-activated temporarily and thus the flyout is dismissed.

Can you articulate your repro so I can confirm any behavior you are seeing?

**Comment by sethcrichton** [comment]
Tim, I’m actually running a hybrid approach that’s somewhere between what
you outlined in your blog post and the templated control that’s part of
Callisto.  Since the control lifecycle is somewhat different, you’re
probably right that deactivating the window and dismissing the flyout will
force it to reinitialize with the new window dimensions.

I will put together another project that uses only the Callisto controls
and see if I can reproduce.

Thanks!
S.

Sent from my Windows 8 PC http://windows.microsoft.com/consumer-preview

 _From:_ Tim Heuer <
reply@reply.github.com

> _Sent:_ Wednesday, June 13, 2012 10:56:02 AM
> _To:_ Seth Crichton sethcrichton@gmail.com
> _Subject:_ Re: [callisto] Settings flyout and layout changes (#46)

Actually Seth, this shouldn't be the case.  If the view launches in full
screen mode, all is well.  The action of a user getting an app to Fill
mode, then the window is de-activated temporarily and thus the flyout is
dismissed.

Can you articulate your repro so I can confirm any behavior you are seeing?

---

**Comment by timheuer** [comment]
Closing as not repro

**Comment by sethcrichton** [comment]
Hey Tim.  Just returned from vacation, and was able to run the Callisto
test application and confirm that the bug I had entered was not
reproducible.  It was obviously an issue in the hybrid code that I had in
my solution.

Sorry for the snipe hunt!

S.

Sent from my Windows 8 PC http://windows.microsoft.com/consumer-preview

 _From:_ Tim Heuer <
reply@reply.github.com

> _Sent:_ Wednesday, June 20, 2012 12:26:09 AM
> _To:_ Seth Crichton sethcrichton@gmail.com
> _Subject:_ Re: [callisto] Settings flyout and layout changes (#46)

Closing as not repro

---

**Comment by sethcrichton** [comment]
Tim, I’ve got another question as it pertains to the VSIX installer
approach to the Callisto controls.  I was having a problem getting my own
installer/extension SDK to work properly, so I thought I would see if I
could use Callisto as a model.

Whether I build the Callisto VSIX from source, or grab it from the gallery,
it installs just fine and I can add controls to a metro application.  The
application runs fine, and I see the controls behaving as I would expect.

However, on the design surface in both VS and Blend, I am getting the
following error:
OutOfMemoryException: Insufficient memory to continue the execution of the
program.
Stack trace:
   at
System.Runtime.InteropServices.WindowsRuntime.IVector`1.InsertAt(UInt32
index, T value)
   at
System.Runtime.InteropServices.WindowsRuntime.VectorToListAdapter.InsertAtHelper[T](IVector`1
_this, UInt32 index, T item)
   at
System.Runtime.InteropServices.WindowsRuntime.VectorToListAdapter.Insert[T](Int32
index, T item)

This is the same error I was seeing on my own control/installer, wondering
if you’ve run across that issue before.

Thanks!
Seth Crichton

Sent from my Windows 8 PC http://windows.microsoft.com/consumer-preview

**Comment by timheuer** [comment]
Yes this is an issue with the designer in the release preview...it should
be fixed by RTM.

---

http://timheuer.com/blog/
twitter: @timheuer

On Wed, Jun 27, 2012 at 3:09 PM, Seth Crichton <
reply@reply.github.com

**Comment by sethcrichton** [comment]
Excellent, thanks for the information.

Sent from my Windows 8 PC http://windows.microsoft.com/consumer-preview

 _From:_ Tim Heuer <
reply@reply.github.com

> _Sent:_ Wednesday, June 27, 2012 10:15:32 PM
> _To:_ Seth Crichton sethcrichton@gmail.com
> _Subject:_ Re: [callisto] Settings flyout and layout changes (#46)

Yes this is an issue with the designer in the release preview...it should
be fixed by RTM.

---

http://timheuer.com/blog/
twitter: @timheuer

On Wed, Jun 27, 2012 at 3:09 PM, Seth Crichton <
reply@reply.github.com

> wrote:
> 
> Tim, I’ve got another question as it pertains to the VSIX installer
> approach to the Callisto controls.  I was having a problem getting my own
> installer/extension SDK to work properly, so I thought I would see if I
> could use Callisto as a model.
> 
> Whether I build the Callisto VSIX from source, or grab it from the
> gallery,
> it installs just fine and I can add controls to a metro application.  The
> application runs fine, and I see the controls behaving as I would expect.
> 
> However, on the design surface in both VS and Blend, I am getting the
> following error:
> OutOfMemoryException: Insufficient memory to continue the execution of the
> program.
> Stack trace:
>   at
> System.Runtime.InteropServices.WindowsRuntime.IVector`1.InsertAt(UInt32
> index, T value)
>   at
> 
> System.Runtime.InteropServices.WindowsRuntime.VectorToListAdapter.InsertAtHelper[T](IVector`1
> _this, UInt32 index, T item)
>   at
> 
> System.Runtime.InteropServices.WindowsRuntime.VectorToListAdapter.Insert[T](Int32
> index, T item)
> 
> This is the same error I was seeing on my own control/installer, wondering
> if you’ve run across that issue before.
> 
> Thanks!
> Seth Crichton
> 
> Sent from my Windows 8 PC http://windows.microsoft.com/consumer-preview
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/timheuer/callisto/issues/46#issuecomment-6616963

---
