### ISSUE TITLE
Settings Flyout no background color

### ISSUE THREAD

**Issue by WalterW** [timheuer/callisto#50]
We test the same code in 2 machines and found out that one of the machine doesn't have any background for the setting flyout panel? Any idea?

**Comment by timheuer** [comment]
WalterW - I can't reproduce this, can you share how you are using it?

**Comment by WalterW** [comment]
hi Tim,

below is my code in VB
  Private Sub OpenFlyout()
        Dim inputPanel As Callisto.Controls.SettingsFlyout

```
        inputPanel = New SettingsFlyout

        With inputPanel
            .HeaderText = "report incident"
            .FlyoutWidth = SettingsFlyout.SettingsFlyoutWidth.Narrow
            .Content = ReportPanel()
            .HeaderBrush = New SolidColorBrush(Colors.DarkGray)
            .Background = New SolidColorBrush(Colors.Gray)
        End With

    _SelectedFlyout = inputPanel
    inputPanel.IsOpen = True
End Sub
```

**Comment by timheuer** [comment]
I still can't repro this.  If you look at the sample app in the project you'll see two lines commented out in the settings example.  when I uncomment these and set the background to Red it shows red.

I also just created a blank VB project and used your code above and it looked fine.  Can you make sure you are using the latest version (1.0.6)
