### ISSUE TITLE
Rating: Binding to Value does not seem to work

### ISSUE THREAD

**Issue by tomKrueger** [timheuer/callisto#51]
I may be doing something wrong.  However, it seems that the binding to Rating.Value does not work when the underlying value is changed.  If I set the Value property without binding the stars show properly.  If the user selects a star the binding fires into the view model. 

Would you have a sample that demonstrates binding to the Rating control.  Specifically binding the underlying value to the rating control on load of the screen to show what a user had rated in the past.

Thanks much,
Tom

**Comment by timheuer** [comment]
I have no problem with binding.  Sample http://sdrv.ms/MoCjwZ - please submit a repro if you are still seeing a problem.

**Comment by tomKrueger** [comment]
Thanks Tim.  It does appear to be working.  In the end it ended up being a oversight.  My apologize for logging an issue and wasting your time.  

Appreciate the help.

Let me know if you need something from me as payback.
Tom

**Comment by timheuer** [comment]
Not a problem...thanks for keeping me on my toes!

On Mon, Jul 2, 2012 at 12:48 PM, tomKrueger <
reply@reply.github.com
