### ISSUE TITLE
WebViewExtension Two-Way Binding Doesn't Seem to Work

### ISSUE THREAD

**Issue by techSage** [timheuer/callisto#53]
The binding now works in one direction (from DataContext to control) thanks (very much!) to your fix (https://github.com/timheuer/callisto/commit/76531d3d32e69f599536913642b033dd58d1e9bc), but not from control to DataContext. I am using a <div> with ContentEditable="true" as the HtmlSource to test this as it allows me to change the Html in the control. When I go to get the HTML content from the DataContext, I still get the same HTML as the DataContext originally held, so it seems that the return to the DataContext isn't happening. I get no DataBinding errors in the Output window, so I don't think I've done the databinding wrong.

Here's my XAML:

```
    <Page.Resources>
        <ResourceDictionary>
            <local:PostContentToViewerHtmlConverter x:Key="posttoviewconverter"></local:PostContentToViewerHtmlConverter>
        </ResourceDictionary>
    </Page.Resources>
...
        <WebView x:Name="blogPostViewer" Margin="0,88" callisto:WebViewExtension.HtmlSource="{Binding Content, Mode=TwoWay, Converter={StaticResource posttoviewconverter}}" />
```

And my Converter that wraps the HTML so that it's editable:

```
    public class PostContentToViewerHtmlConverter : IValueConverter
    {
        #region Constants
        const string editorBaseHTMLPrefix = "<html><head></head><body><div id='postContent' contenteditable='true'>";
        const string editorBaseHTMLSuffix = "</div></body></html>"; 
        #endregion

        public object Convert(object value, Type targettype, object parameter, string language)
        {
            return editorBaseHTMLPrefix + value + editorBaseHTMLSuffix;
        }

        public object ConvertBack(object value, Type targettype, object parameter, string language)
        {
            return value.ToString().Replace(editorBaseHTMLPrefix, "").Replace(editorBaseHTMLSuffix, "");
        }
    }
```

Would you like me to make a repro using the new WebViewExtension sample in the SampleApp?

**Comment by techSage** [comment]
Fixed code for converter getting hosed by the markup scrubber in my OP.

**Comment by timheuer** [comment]
TwoWay binding wouldn't work here for this attached property.  The content
within the WebView isn't a XAML element and isn't announcing changes to the
XAML visual tree.

On Fri, Jul 6, 2012 at 9:03 AM, techSage <
reply@reply.github.com

**Comment by techSage** [comment]
Ok, I thought that might be the case that it wasn't supported, but wanted to check. Thanks for your response.

As a workaround, I guess I'll continue to use the .InvokeScript("eval"...) + ScriptNotify combo I've been using to get content back out of the WebView. I looked into using .GetHtmlSource, but it doesn't seem to return an up-to-date version of the HTML source either (maybe this is expected, but I haven't looked into it).

Thanks again for the other fix.

**Comment by timheuer** [comment]
The GetHtmlSource is a good one, but yes seems an artifact of the WebView
not really announcing the content changed.  :-(

---

http://timheuer.com/blog/
twitter: @timheuer

On Fri, Jul 6, 2012 at 12:57 PM, techSage <
reply@reply.github.com

**Comment by techSage** [comment]
Ok, thanks for the follow-up. I find it ironic that there’s so much support for HTML/JS dev for Win8 and yet the WebView control for XAML dev is so stripped-down. Hopefully this changes at some point.
