### ISSUE TITLE
Flyout doesn't work in Settings

### ISSUE THREAD

**Issue by zubairahmed-ai** [timheuer/callisto#54]
Hi,

I followed your blog entry and example on this project page to use Flyout control for Settings page in my http://metrorssreader.codeplex.com,

It looks like I need to specify PlacementTarget element even for use in Settings, which throws an exception when not specified,

Please help.

**Comment by timheuer** [comment]
Yes, PlacementTarget is required.  The use of a Flyout within a SettingsFlyout is not supported.  This does not match good guidelines for what should be in a Settings experience to begin with, but this isn't a scenario that I've looked to support.  Sorry.
