### ISSUE TITLE
Settings Flyout _contentGrid is null

### ISSUE THREAD

**Issue by zubairahmed-ai** [timheuer/callisto#55]
Hi,

Using SettingsFlyout control the following throws an exception, I tried adding a Grid with that Name, doesn't work

 _contentGrid = GetTemplateChild("SettingsFlyoutContentGrid") as Grid;

Is this a issue or am I missing something?

**Comment by timheuer** [comment]
Please tell me how you are including it in your project and your code. See the test app that comes with the project for an example. 

-th

**Comment by timheuer** [comment]
When used properly this is not a repro.  I think that you may be just including the code without using a reference or the nuget package.  Please see installation notes in the readme.

**Comment by zubairahmed-ai** [comment]
You are right, I was including the source code in the project, installing and using via VSIX solves the issue, still wondering why?

But anyway, thanks for help

**Comment by timheuer** [comment]
Because you didn't have the generic.xaml definition. 

-th

**Comment by zubairahmed-ai** [comment]
Oh that explains, thanks
