### ISSUE TITLE
Allow to set the Margin of the Content in the Settings Flyout to 0

### ISSUE THREAD

**Issue by pedropaf** [timheuer/callisto#58]
I have created a user control that I want to use as the content for my Settings Flyout. It's possible, but the flyout seems to add a default margin of about 20px. It would be nice to set that margin to 0 and I could control the whole content section.

Thanks

**Comment by timheuer** [comment]
I will probably close this as the design of the settings area in the ui
guidelines has these margins set.

On Tuesday, July 10, 2012, pedropaf wrote:

> I have created a user control that I want to use as the content for my
> Settings Flyout. It's possible, but the flyout seems to add a default
> margin of about 20px. It would be nice to set that margin to 0 and I could
> control the whole content section.
> 
> Thanks
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/timheuer/callisto/issues/58

## 

---

http://timheuer.com/blog/
twitter: @timheuer

**Comment by pedropaf** [comment]
I think that it's nice to have it by default, but giving access to the whole  flyout is a need in some cases. 

In my specific case, I wanted to have a thin subtle horizontal line from edge to edge to separate some areas, more for design purposes than anything else. 

Thanks for the great work. 

Pedro

**Comment by timheuer** [comment]
horizontal line should be fine...put that in your usercontrol and set the
usercontrol as content

---

http://timheuer.com/blog/
twitter: @timheuer

On Tue, Jul 10, 2012 at 12:15 PM, pedropaf <
reply@reply.github.com

> wrote:
> 
> I think that it's nice to have it by default, but giving access to the
> whole  flyout is a need in some cases.
> 
> In my specific case, I wanted to have a thin subtle horizontal line from
> edge to edge to separate some areas, more for design purposes than anything
> else.
> 
> Thanks for the great work.
> 
> Pedro
>

**Comment by diegopoza** [comment]
Please consider the following scenario:
I have a content that needs scrolling (Disclaimer). If I put the ScrollViewer in my user control it is separated 20px from the right side, and it doesn't feel ok. How can I make the scroll bar appear in the right side of the FlyoutSettings when the content overflows the flyout's height?
