### ISSUE TITLE
want menu selection events

### ISSUE THREAD

**Issue by ghost** [timheuer/callisto#61]
Hi, I am using menu in flyout control, but I don't want to use separate tap/click event for each menuitem. I am using listview for menu's control template. My menu is having nearly 100+ menuitems. So is there any workaround for selection menu event like we use in combo box ?

**Comment by timheuer** [comment]
I don't see this as a Callisto issue, so I'll be closing this.

If you want menu events in your listbox, why not just get the
selectionchanged event.  Also, 100 items in a menu!?!?!?!

---

http://timheuer.com/blog/
twitter: @timheuer

On Thu, Jul 19, 2012 at 12:24 AM, farhan-ghumra <
reply@reply.github.com

**Comment by ghost** [comment]
Menu doesn't has selectionchanged event. I am using listbox by modifying
"Callisto\themes\Generic.xaml" as line # 257. I have changed ControlTemplate to
list box, now how can I get menu event not the seperate menuitem click
event ?

On Thu, Jul 19, 2012 at 2:51 PM, Tim Heuer <
reply@reply.github.com

> wrote:
> 
> I don't see this as a Callisto issue, so I'll be closing this.
> 
> If you want menu events in your listbox, why not just get the
> selectionchanged event.  Also, 100 items in a menu!?!?!?!
> 
> ---
> 
> http://timheuer.com/blog/
> twitter: @timheuer
> 
> On Thu, Jul 19, 2012 at 12:24 AM, farhan-ghumra <
> reply@reply.github.com
> 
> > wrote:
> > 
> > Hi, I am using menu in flyout control, but I don't want to use separate
> > tap/click event for each menuitem. I am using listview for menu's control
> > template. My menu is having nearly 100+ menuitems. So is there any
> > workaround for selection menu event like we use in combo box ?
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/timheuer/callisto/issues/61
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/timheuer/callisto/issues/61#issuecomment-7116427

## 

Farhan Ghumra
Simform Solutions Pvt. Ltd.
Windows 8 Metro Style App Developer

+91 94266 63586
+91 97254 63586
+91 74057 49752

**Comment by timheuer** [comment]
Yes, Menu doesn't have that event but your ListBox does.

You also don't need a separate event for each Menu if you want to go that
way -- you could use the same method and inspect the Tag value that you can
set to some param.

---

http://timheuer.com/blog/
twitter: @timheuer

On Fri, Jul 20, 2012 at 4:04 AM, farhan-ghumra <
reply@reply.github.com
