### ISSUE TITLE
Flyout is dismissed if clicked before entrance animation is completed

### ISSUE THREAD

**Issue by KasperHoldum** [timheuer/callisto#62]
I use the example code given in the documentation to display a flyout that displays a textbox within a custom control. However, if you click the textbox before the animation is 100% complete (which takes a few seconds even after it enters the screen) then the flyout is dismissed.

Is there any way to allow for click even while the control is being animated? Or in worst case disable the animation completely?

```
        addLocationFlyout = new Flyout();
        addLocationFlyout.Content = addFavoritePlaceControl;
        addLocationFlyout.Placement = PlacementMode.Top;
       addLocationFlyout.PlacementTarget = this.AddLocationAppBarButton; // this is an UI element (usually the sender)

        LayoutRoot.Children.Add(addLocationFlyout.HostPopup); // add this to some existing control in your view like the root visual

        //remove the parenting during the Closed event on the Flyout
        addLocationFlyout.Closed += (s, a) =>
        {
            LayoutRoot.Children.Remove(addLocationFlyout.HostPopup);
        };


        addLocationFlyout.IsOpen = true;
```

**Comment by timheuer** [comment]
I can't repro this because I can't click fast enough apparently :-)  Do you really expect users to click faster than the animation completes?

**Comment by jasonmoore2k** [comment]
I found the same problem.  The animation isn't really that fast, so I can definitely see users running into this.

**Comment by KevinDockx** [comment]
I've noticed this as well, but I think it doesn't have to do with the Flyout control per sé.  In the original issue description, I notice the poster talks about "a few seconds" for the animation.  Noticed that as well in the app I'm working on.  However, the normal animation for the Flyout to appear is, as Tim states, so short it's very, very hard to click too soon so the control is dismissed.

I also noticed that, although I set the Placement to Bottom (which would mean the animation would slide in from there), the animation I saw was starting from the right of the screen.  

What's happening:
- I rooted the control to the parent grid of the current View in the current frame (to ensure it moves up when the virtual keyboard is invoked).
- The parent root of that current view has a style defined (happens by default for pages you add), the "LayoutRoot"-style.  This is a built-in style which includes animating all children with an "entrance in"-animation from the right of the screen (you can notice that easily by navigating between a few pages in your app which have that style defined on their root grid - you'll see your "page" slide in).  
- By adding the Flyout control to the children-collection of that grid, you automatically trigger the entrance-animation that's applied on all items that are added to the grid: this is the animation we notice (slide in from the right), and that one does indeed take a few seconds.

The solution?  Well, you could simply remove the style from your root grid, but then you don't get the nice "slide-in" animation when you navigate to a page.  I eventually solved it by rooting the Flyout control to a grid I defined as a child of the root grid.  This new grid doesn't have any style defined, so when I add the Flyout control to that grid to root it in the visual tree, I get the nice & short "from bottom"-animation I would expect.  And that one's so fast I don't have time to click before it's done :)

At least, all of the above is what I think after some experimentation :-)  Hope this helps!

**Comment by Nyami** [comment]
Same issue here but KevinDockx's solution worked a treat.

**Comment by Nyami** [comment]
I should have added that to reproduce this behaviour add the style LayoutRootStyle to the the grid "FrameLayoutRoot"in MainPage.xaml of the test application and use the Flyout from the Appbar.
