### ISSUE TITLE
Should add a note in the documentation that Callistro requires styles from StandardStyles.xaml or copy required styles into Generic.xaml

### ISSUE THREAD

**Issue by aschearer** [timheuer/callisto#67]
Tried to add Callistro to a project which was not using StandandStyles.xaml. In this case was using only the SettingsFlyout. Launching the flyout would cause the program to crash due to an exception:

> "System.Runtime.InteropServices.COMException: Unspecified error\r\n\r\n   at Windows.UI.Xaml.FrameworkElement.MeasureOverride(Size availableSize)"

I believe the required style is `BackButtonStyle` and its dependencies.

**Comment by timheuer** [comment]
This shouldn't be the case. Back button style is defined in the control itself

-th

**Comment by aschearer** [comment]
Here's a [test project](http://www.anotherearlymorning.com/example/TestSettingsFlyout.zip) which demonstrates the issue. 
1. Run app
2. Launch settings charm
3. Click "About" 

Expected: Flyout appears normally
Observed: App crashes

Go to App.xaml and uncomment Styles.xaml resource and repeat steps above:
Observed: Flyout appears normally

**Comment by timheuer** [comment]
Yep, got it.  My bad.  The glyph (BackButtonSnappedGlyph) I the issue.
I'll move this to a control style to remove the dependency.  Apologies for
the issue.

**Comment by aschearer** [comment]
Great, just glad I could help. (And even happier I got it working on my end). Thanks for making this available. Definitely saved me some time!
