### ISSUE TITLE
Flyout touch SIP issue

### ISSUE THREAD

**Issue by rudigrobler** [timheuer/callisto#70]
Flyout do not re-adjust position if SIP is displayed (and overlapping) the flyout

Recreate:
1. Create a app bar button
2. On click create a flyout with a textbox inside
3. Run app in simulator and turn on touch simulation
4. Open appbar and click on button

Flyout is now behind the SIP

**Comment by timheuer** [comment]
You need to parent your flyout in the visual tree if you want this effect. See the test app in an example of this. 

-th

**Comment by rudigrobler** [comment]
It is parented to the button?

**Comment by timheuer** [comment]
Likely no, the button is just triggering it.

**Comment by rudigrobler** [comment]
I used the following code:

Flyout f = new Flyout();
f.PlacementTarget = sender as UIElement;
f.Placement = PlacementMode.Top;
f.Content = new TextBox() { Width = 200 };
f.IsOpen = true;

Where sender is the button inside the AppBar?

Once you click inside the TextBox, the SIP overlap the flyout?

**Comment by timheuer** [comment]
That does not parent the flyout. You need to add the HostPopup as a child element of some visual element (that supports children)

PlacementTarget is used for positioning not parenting. 

-th
