### ISSUE TITLE
Flyout in snapped view

### ISSUE THREAD

**Issue by Pengguangwu** [timheuer/callisto#71]
I got a unhandled Win32 exception when trying to use the flyout control in snapped view. Otherwise the flyout control works in full mode. I am not proficient in debugging so I am looking for some pointers here. There seems to have enough area for a small flyout. Thanks.

**Comment by timheuer** [comment]
it isn't advisable to use a flyout in snapped view.  If your app function requires that you should use TryUnsnap first to get the app back in 'normal' usability to do those types of actions.  But I will look at this...do you have a repro?  My guess is that the flyout didn't have enough space to draw in the snapped area based on the measurements in needed.

**Comment by Pengguangwu** [comment]
Does "Repro" mean reproducing the error? I probably clicked too far last time. The initial unhandled exception is:Exception = {"Object reference not set to an instance of an object."}Message = "System.NullReferenceException\r\n   at Callisto.Controls.Flyout.PerformPlacement(Double horizontalOffset, Double verticalOffset)\r\n   at Callisto.Controls.Flyout.OnHostPopupOpened(Object sender, Object e)"
 It is at the line  flyout.IsOpen = true.  The size of the border is 200 (w)x400(h).This is a nice-to-have item in the snapped view so I do not have to add. Or I can add another page to navigate to (text info only). Thank you.Date: Tue, 28 Aug 2012 09:39:51 -0700

**Comment by timheuer** [comment]
NullReference -- this seems like you aren't setting the PlacementTarget
element perhaps?

if you have a sample app that exhibits the issue that will help accelerate
investigation.

---

http://timheuer.com/blog/
twitter: @timheuer

**Comment by Pengguangwu** [comment]
Sorry my bad. I forgot to change the gridview item to listview item in the containter type. The flyout works fine now. Thank you for the help and appreciate very much the controls you wrote.
 Date: Tue, 28 Aug 2012 10:16:43 -0700

**Comment by timheuer** [comment]
Based on bug logger, closing.
