### ISSUE TITLE
.isOpen generating an exception

### ISSUE THREAD

**Issue by edulorenzo** [timheuer/callisto#78]
Current code (from sample)

 Flyout f = new Flyout();

```
        Border b = new Border();
        b.Width = 300;
        b.Height = 125;

        TextBlock tb = new TextBlock();
        tb.HorizontalAlignment = Windows.UI.Xaml.HorizontalAlignment.Center;
        tb.VerticalAlignment = Windows.UI.Xaml.VerticalAlignment.Center;
        tb.TextWrapping = TextWrapping.Wrap;
        tb.FontSize = 24.667;
        tb.Text = "This is a basic ContentControl so put anything you want in here.";

        b.Child = tb;

        f.Content = b;

        f.Placement = (PlacementMode)Enum.Parse(typeof(PlacementMode), positioning.SelectionBoxItem.ToString());
        f.PlacementTarget = sender as UIElement;

        f.IsOpen = true;

        ObjectTracker.Track(f);
```

f.IsOpen = true; <-- this line is throwing an exception

 at Windows.UI.Xaml.Controls.Primitives.Popup.put_IsOpen(Boolean value)

   at Callisto.Controls.Flyout.<.cctor>b__3(DependencyObject obj, DependencyPropertyChangedEventArgs args)

**Comment by edulorenzo** [comment]
update: My callisto dll must be outdated, i replaced with Runtime v4.0.30319 and it does not throw exception anymore, BUT goes to here and does not render on the app

#if DEBUG && !DISABLE_XAML_GENERATED_BREAK_ON_UNHANDLED_EXCEPTION
            UnhandledException += (sender, e) =>
            {
                if (Debugger.IsAttached) Debugger.Break();
            };
#endif

**Comment by timheuer** [comment]
If you are not running RTM, you cannot use the latest and must stay on
1.0.10.  The latest version is for RTM only.

---

http://timheuer.com/blog/
twitter: @timheuer
