### ISSUE TITLE
Flyout closing doesn't update IsOpen

### ISSUE THREAD

**Issue by stefanolson** [timheuer/callisto#79]
When the flyout gets closed by clicking outside of it, IsOpen is not set to false.  I would suggest this change:
In Flyout.OnHostPopupClosed

IsOpen = false;

**Comment by timheuer** [comment]
The object is gone at this point though...is this causing an issue for you?  if so, what's the use case here?  I'm not disagreeing that the value isn't being set, but it shouldn't have an impact as the dismissal of the flyout removes the object.

**Comment by stefanolson** [comment]
What I'm doing at the moment, in order to be maximise the code sharing with WPF and windows phone, where I'm using a context menu, is not recreating the fly out every time it is needed.  So, when they click requiring the menu to appear I set IsOpen to true.  Unfortunately if it hasn't been set to false then setting it to true does nothing.
