### ISSUE TITLE
Flyout placement is wrong if HostPopup's parent is set.

### ISSUE THREAD

**Issue by lukasf** [timheuer/callisto#82]
If I add the host popup to the layout root, then the flyout's placement is off. The offset values from the popup are not interpreted as relative to the window but relative to the parent control, if a parent is set.

This can be easily fixed with the following code in PerformPlacement:

```
        ...
        // fix placement if popup's parent is set
        UIElement parent = _hostPopup.Parent as UIElement;
        if (parent != null)
        {
            var transform = parent.TransformToVisual(Window.Current.Content);
            var offset = transform.TransformPoint(new Point(0, 0));
            calcH -= offset.X;
            calcY -= offset.Y;
        }

        // now assign offset values
        _hostPopup.HorizontalOffset = calcH;
        _hostPopup.VerticalOffset = calcY;
        ...
```

Cheers, Lukas

**Comment by timheuer** [comment]
Can you provide me with a repro project showing the issue?  The test app has one that roots it to the frame root and it works fine...so I want to make sure I understand the fix.  Thanks for this though!

**Comment by lukasf** [comment]
Change ShowFlyoutMenu2 like below and then click "Show Menu". Placement 
will be offset by some amount. Changing as per my suggestion fixes the 
placement issue. I think in ShowFlyoutMenu3  it only works because there it 
is parented to the application's root grid, which fills the whole sceen. 
Then there will be no offset issues. This only appears if the parent does 
not cover the whole window.

Here I set the Parent to the LayoutRoot of the sample page, which is 
positioned next to the sample selection menu:

private void ShowFlyoutMenu2(object sender, RoutedEventArgs e)
        {
            Flyout f = new Flyout();
            LayoutRoot.Children.Add(f.HostPopup);

            Border b = new Border();
            b.Width = 300;
            b.Height = 125;

            TextBlock tb = new TextBlock();
            tb.HorizontalAlignment = 
Windows.UI.Xaml.HorizontalAlignment.Center;
            tb.VerticalAlignment = 
Windows.UI.Xaml.VerticalAlignment.Center;
            tb.TextWrapping = TextWrapping.Wrap;
            tb.FontSize = 24.667;
            tb.Text = "This is a basic ContentControl so put 
anything you want in here.";

            b.Child = tb;

            f.Content = b;

            f.Placement = 
(PlacementMode)Enum.Parse(typeof(PlacementMode), 
positioning.SelectionBoxItem.ToString());
            f.PlacementTarget = sender as UIElement;
            
            f.IsOpen = true;

            f.Closed += delegate { 
LayoutRoot.Children.Remove(f.HostPopup); };

            ObjectTracker.Track(f);
        }

**Comment by timheuer** [comment]
Got it.  I'll make this change, but I'm also adding a change that doesn't make it totally necessary to add the HostPopup to the visual tree (if only doing so to get the keyboard scrollintoview functionality).
