### ISSUE TITLE
SettingsFlyout vs CharmFlyout

### ISSUE THREAD

**Issue by RehanSaeed** [timheuer/callisto#88]
Hi,

Great set of supplemental code. I'm looking into adding a SettingsFlyout to my app. I found the CharmFlyout:

http://w8isms.blogspot.co.uk/2012/07/charmflyout-another-charming.html

After reading his articles, its really easy to use and allows you to have sub-settings pages and to share settings pages between different pages of your application. Perhaps you could collaborate and combine your knowledge?

**Comment by timheuer** [comment]
I'd be interested what you don't find easy to use about SettingsFlyout?  Regardless, Callisto has an existing user base right now and we don't want to break compatibility.  The controls were developed well before the final release of Windows 8 and as such, have some things that I wish were different, but again needed to maintain compatibility.  Namely declarative support isn't great.  However, SettingsFlyout should be seen as a content control and developers should create a UserControl to set as the content here.

In analysis of the store apps, there isn't a lot of sub-settings pages.  Additionally you could absolutely share settings across your entire app by creating your settings commands from within the App object.
