### ISSUE TITLE
Getting error in source while compiling

### ISSUE THREAD

**Issue by FarhanGhumra** [timheuer/callisto#89]
Hi, I have downloaded the repo of latest Callisto controls, while compiling I am getting these two errors. I am using VS 2012 RC and Windows 8 Release Preview
1. Unknown member 'IsDeferredScrollingEnabled' on element 'ScrollViewer'    D:\timheuer-callisto-8a73f62\src\Callisto\themes\Generic.xaml
2. The type or namespace name 'VisualElement' does not exist in the namespace 'Callisto.Controls.Common' (are you missing an assembly reference?)   D:\timheuer-callisto-8a73f62\src\Callisto.TestApp\App.xaml.cs

Please suggest me solution.

**Comment by timheuer** [comment]
Please ensure you are using the RTM version of Windows.
