### ISSUE TITLE
Color conversion leads to exception in german apps

### ISSUE THREAD

**Issue by ghost** [timheuer/callisto#96]
The line
var factor = System.Convert.ToDouble(parameter);
inside the color converter is missing the culture, so it assumes the provided string to be in the same culture as the app that is running. In case of a german language app, the provided value "0.8" is converted to value "8".

Solution:
var factor = System.Convert.ToDouble(parameter, CultureInfo.InvariantCulture);

**Comment by timheuer** [comment]
Yikes, my deepest apologies...fixing now.
