### ISSUE TITLE
SettingsFlyout appears under WebView when opened

### ISSUE THREAD

**Issue by realworld666** [timheuer/callisto#97]
The sort order appears to be wrong when a WebView is up against the right of the screen. Opening a settings window shows under the WebView when a SettingsFlyout is opened. The MS default settings screens appear on top. I have not tested this with other UI elements

**Comment by timheuer** [comment]
Not a bug for SettingsFlyout.  WebView content always owns the z-order.  One thing you can do is that when the SettingsFlyout is displayed, you can change to a WebViewBrush.  This is not a bug however that I can solve.
