### ISSUE TITLE
SettingsFlyout.OnLoaded doesn't check for null on rootBorder

### ISSUE THREAD

**Issue by dotMorten** [timheuer/callisto#99]
If the template is overridden and a rootBorder part not provided (or template isn't loading at all), a null-reference exception could be thrown because rootBorder isn't checked for null before assigning the margin to it.

**Comment by dotMorten** [comment]
...same issue with 'contentGrid' in OnApplyTemplate.

**Comment by timheuer** [comment]
Noted. Is there a reason you would remove those parts?

-th
